set-option -g prefix M-a
bind-key M-a send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -sg terminal-overrides ",*:RGB"
set-option -g set-clipboard on

set -g history-limit 50000
set -sg escape-time 0
setw -g mouse on

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


set-option -g status-position top
set -g status-bg "set -g status-fg colour7
set -g status-justify left
set-option -g status-left ' '
set -g status-right-length 150

set -g window-status-separator " | "
set -g window-status-format "set -g window-status-current-format "#[fg=#50fa7b]#W"

set -g @dracula-bg 'set -g @dracula-current-line 'set -g @dracula-fg 'set -g @dracula-comment 'set -g @dracula-cyan 'set -g @dracula-green 'set -g @dracula-orange 'set -g @dracula-pink 'set -g @dracula-purple 'set -g @dracula-red 'set -g @dracula-yellow '
set -g status-position top
set -g status-style "bg=set -g status-right "#[fg=#{@dracula-yellow}]P: #(tmux_status_path.sh '#{session_path}') #[fg=#{@dracula-purple}] S: #{=10:session_name} #[fg=#{@dracula-pink}]#{?client_prefix, ● ,} "

setw -g window-status-separator ""
setw -g window-status-format "#[fg=#{@dracula-comment}] #I #W "
setw -g window-status-current-format "#[bg=#{@dracula-current-line},fg=#{@dracula-cyan},bold] #I #W "

set -g pane-border-style "fg=set -g pane-active-border-style "fg=

bind -n M-b switch-client -l
bind -n M-u run-shell "tmux_harpoon_switch.sh 1"
bind -n M-i run-shell "tmux_harpoon_switch.sh 2"
bind -n M-o run-shell "tmux_harpoon_switch.sh 3"
bind -n M-p run-shell "tmux_harpoon_switch.sh 4"


bind t run-shell "tmux_notify_toggle.sh -t -s"
bind r run-shell "tmux_notify_toggle.sh -d -s"

bind s run-shell "tmux_harpoon_add.sh"
bind i run-shell "tmux_harpoon_edit.sh"
bind o run-shell "tmux_create_or_switch_window.sh"

bind q confirm-before -p "Kill window? (y/n)" kill-window
bind g display-popup -w 40% -E "tmux_workspace.sh"
bind w display-popup -w 80% -h 80% -E "tmux_sessionizer.sh"

bind-key V run-shell "tmux_edit_tmux_history.sh"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind y run-shell "tmux capture-pane -pS -2500 | tmux_copy_last_output.sh"

set-window-option -g mode-keys vi
bind v copy-mode

bind-key e copy-mode \  '((^|/|\<|[[:space:]"])[[:alnum:]~_."-]*|(\.|\.\.))((/[][[:alnum:]_.bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'gclip'
bind-key -T copy-mode-vi o send-keys -X copy-pipe-and-cancel "tmux_harpoon_open_in_hx.sh '
bind -T copy-mode-vi g switch-client -T visg
bind -T visg h send -X start-of-line \bind -T visg s send -X start-of-line \bind -T visg l send -X end-of-line \bind -T visg g send -X top-line \bind -T visg e send -X bottom-line \