# AUTO-GENERATED by modules/theme. Do not edit. Run `nix build .#diagrams-theme && cp -f --no-preserve=mode result modules/diagrams/theme.nix`.

{
  fleetPalette = [
    {
      border = "#1d4ed8";
      fill = "#bfdbfe";
    }
    {
      border = "#15803d";
      fill = "#bbf7d0";
    }
    {
      border = "#c2410c";
      fill = "#fed7aa";
    }
    {
      border = "#6d28d9";
      fill = "#ddd6fe";
    }
    {
      border = "#a16207";
      fill = "#fef08a";
    }
    {
      border = "#be185d";
      fill = "#fbcfe8";
    }
    {
      border = "#047857";
      fill = "#a7f3d0";
    }
    {
      border = "#be123c";
      fill = "#fda4af";
    }
  ];
  fleetSolo = {
    border = "#94a3b8";
    fill = "#f1f5f9";
  };
  fontFamily = "DejaVu Sans, Helvetica, Arial, sans-serif";
  fontFamilyGraphviz = "DejaVu Sans";
  fontSize = {
    body = 10;
    edge = 9;
    label = 11;
    small = 8;
    subtitle = 14;
    tiny = 7;
    title = 18;
  };
  palette = {
    background = "#ffffff";
    cluster = "#e2e8f0";
    computeBg = "#bbf7d0";
    computeBorder = "#15803d";
    controllerBg = "#fed7aa";
    controllerBorder = "#c2410c";
    danger = "#dc2626";
    dangerBg = "#fecaca";
    edgeDefault = "#374151";
    edgeDownlink = "#15803d";
    edgeMgmt = "#6b21a8";
    edgeMlag = "#b91c1c";
    edgeUplink = "#1d4ed8";
    external = "#ffffff";
    gridLine = "#e2e8f0";
    host = "#dcfce7";
    hostPlanned = "#fef9c3";
    hostRetired = "#fecaca";
    laneCluster = "#f1f5f9";
    laneHost = "#f0fdf4";
    laneTeam = "#faf5ff";
    laneUser = "#fff7fb";
    legendBorder = "#94a3b8";
    network = "#fef3c7";
    panelBg = "#f8fafc";
    panelBorder = "#cbd5e1";
    partitionBg = "#fef08a";
    partitionBorder = "#a16207";
    rack = "#f3f4f6";
    site = "#ffedd5";
    submitBg = "#bfdbfe";
    submitBorder = "#1d4ed8";
    switch = "#dbeafe";
    team = "#f3e8ff";
    text = "#111827";
    textFaint = "#475569";
    textMuted = "#374151";
    user = "#fce7f3";
  };
  radius = {
    large = 0.45;
    medium = 0.18;
    small = 0.1;
  };
  stroke = {
    heavy = 0.2;
    medium = 0.1;
    thick = 0.16;
    thin = 0.06;
  };
  strokeWidthPt = {
    hairline = 0.3;
    medium = 1.2;
    normal = 1.0;
    thick = 1.5;
    thin = 0.5;
  };
}
