#!/bin/sh /etc/rc.common
# shellcheck shell=sh
# shellcheck disable=SC1091,SC2034,SC3043

USE_PROCD=1
START=99
STOP=01

. /lib/router-captive.sh

start_service() {
  local enabled
  config_load router
  config_get enabled captive enabled 1

  [ "$enabled" = "0" ] && return 0

  procd_open_instance router-captive-watchdog
  procd_set_param command /usr/libexec/router-captive-watchdog
  procd_set_param respawn 5 5 0
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

stop_service() {
  if router_captive_bypass_active; then
    logger -t router-captive "service stopping, restoring dns rebind protection"
    router_captive_restore
  fi
}

service_triggers() {
  procd_add_reload_trigger router
}

reload_service() {
  stop
  start
}
