#!/bin/sh /etc/rc.common

export USE_PROCD=1
export START=18
export STOP=89

start_service() {
	procd_open_instance
	procd_set_param command /usr/libexec/router-dns-telemetry
	procd_set_param respawn 5 1 -1
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
