#!/bin/sh /etc/rc.common
# shellcheck shell=sh
# shellcheck disable=SC2034

USE_PROCD=1
START=98
STOP=02

start_service() {
	procd_open_instance router-net-watchdog
	procd_set_param command /usr/libexec/router-net-watchdog
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger router
}

reload_service() {
	stop
	start
}
