#!/bin/sh /etc/rc.common
# shellcheck shell=sh
# shellcheck disable=SC1091,SC2034,SC3043

USE_PROCD=1
START=99
STOP=01

. /lib/router-fan-modes.sh

start_service() {
	local mode manual_pwm safety_temp safety_interval
	config_load router
	config_get mode             fan mode             auto
	config_get manual_pwm       fan manual_pwm       128
	config_get safety_temp      fan safety_temp      85000
	config_get safety_interval  fan safety_interval  5

	router_fan_apply_mode "$mode" "$manual_pwm"
	logger -t router-fan "boot: applied mode=$mode pwm=$manual_pwm (safety=${safety_temp}mC, interval=${safety_interval}s)"

	procd_open_instance router-fan-watchdog
	procd_set_param command /usr/libexec/router-fan-watchdog
	procd_set_param respawn 5 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger router
}

reload_service() {
	stop
	start
}
