alias:
# - "seer:No LLM fits the bill"
- "sage:claude-opus-4-20250514"
- "adept:gemini/gemini-2.5-pro"
- "scribe:gemini/gemini-2.5-flash"
- "imp:gemini/gemini-2.5-flash-lite-preview-06-17"

model: adept
cache-prompts: true
dark-mode: true
git: false
auto-commits: false
dirty-commits: false
analytics-disable: true
check-update: false
show-release-notes: false
auto-lint: false
notifications: true # to deal with +1 min latency on average
notifications-command: "ffplay -autoexit -nodisp -af 'volume=2.0' $HOME/.local/share/sounds/effects/nier_enter.mp3 &>/dev/null 2>&1"
