alias:
# - "seer:No LLM fits the bill"
- "sage:claude-opus-4-20250514"
- "adept:gemini/gemini-2.5-pro"
- "scribe:gemini/gemini-2.5-flash"
- "imp:gemini/gemini-2.5-flash-lite-preview-06-17"

model: adept
cache-prompts: true
# dark-mode: true
git: false
auto-commits: false
dirty-commits: false
analytics-disable: true
check-update: false
show-release-notes: false
auto-lint: false
notifications: true # to deal with +1 min latency on average
notifications-command: "ffplay -autoexit -nodisp -af 'volume=2.0' $HOME/.local/share/sounds/effects/nier_enter.mp3 &>/dev/null 2>&1"

# Theme
code-theme                      : dracula
user-input-color                : "#bd93f9"
tool-output-color               : "#8be9fd"
tool-error-color                : "#ff5555"
tool-warning-color              : "#f1fa8c"
assistant-output-color          : "#50fa7b"
completion-menu-color           : "#f8f8f2"
completion-menu-bg-color        : "#282a36"
completion-menu-current-color   : "#44475a"
completion-menu-current-bg-color: "#ff79c6"
