# AUTO-GENERATED by modules/home/common/theme/tones.py. Do not edit.
# Regenerate with `nix build .#theme-tones && cp -f result modules/home/common/theme/tones.nix`.
{
  seed = "#282a36";
  hue = 276.7743;
  chroma = 11.3633;

  neutral = {
    "4" = "#0b0e18";
    "6" = "#11131e";
    "10" = "#191b26";
    "12" = "#1d1f2b";
    "17" = "#272935";
    "20" = "#2e303c";
    "22" = "#323440";
    "24" = "#373845";
    "30" = "#444653";
    "60" = "#8f909e";
    "80" = "#c5c5d5";
    "90" = "#e1e1f1";
  };

  onAccent = {
    cyan = "#00363e";
    green = "#003912";
    orange = "#492900";
    pink = "#620044";
    purple = "#411478";
    red = "#5c000a";
    yellow = "#2f3300";
  };

  accentContainer = {
    cyan = "#004e5a";
    green = "#00531e";
    orange = "#683c00";
    pink = "#860f60";
    purple = "#593090";
    red = "#930016";
    yellow = "#454b00";
  };

  onAccentContainer = {
    cyan = "#a3eeff";
    green = "#69ff88";
    orange = "#ffdcbc";
    pink = "#ffd8e9";
    purple = "#eddcff";
    red = "#ffdad7";
    yellow = "#e1ea7e";
  };

  accentFixed = {
    cyan = "#a3eeff";
    green = "#69ff88";
    orange = "#ffdcbc";
    pink = "#ffd8e9";
    purple = "#eddcff";
    red = "#ffdad7";
    yellow = "#e1ea7e";
  };

  accentFixedDim = {
    cyan = "#75d4e8";
    green = "#31e368";
    orange = "#ffb86c";
    pink = "#ffafd7";
    purple = "#d7baff";
    red = "#ffb3ae";
    yellow = "#c5cd65";
  };
}
