"""Derive the HCT tonal values used by the Dracula/Material 3 bridge.

Emits modules/home/common/theme/tones.nix. Build with `nix build .#theme-tones`
and apply with `cp -f result modules/home/common/theme/tones.nix`.

The neutral ramp is Dracula's own neutral line: the hue and chroma of the
Dracula spec Background reproduce Background, Selection and AnsiBlack at their
natural tones, so extending it to the Material 3 dark surface tones adds depth
steps without introducing a new hue.

Accent on-colours follow the Material 3 dark-scheme rule: the on-colour for an
accent is drawn from that accent's own tonal palette, starting at tone 20 and
darkening until it satisfies the 4.5:1 contrast floor that Material 3 states as
ContrastCurve(4.5, 7, 11, 21) for on-accent roles.
"""

import sys

from materialyoucolor.hct import Hct
from materialyoucolor.palettes.tonal_palette import TonalPalette

SEED = "#282a36"

NEUTRAL_TONES = [4, 6, 10, 12, 17, 20, 22, 24, 30, 60, 80, 90]

ACCENTS = {
    "red": "#ff5555",
    "orange": "#ffb86c",
    "yellow": "#f1fa8c",
    "green": "#50fa7b",
    "purple": "#bd93f9",
    "cyan": "#8be9fd",
    "pink": "#ff79c6",
}

ON_ACCENT_START_TONE = 20
ACCENT_CONTAINER_TONE = 30
ON_ACCENT_CONTAINER_START_TONE = 90
MIN_CONTRAST = 4.5

# Material 3 "fixed" roles hold the same value in light and dark schemes and are
# the published way to reach a lighter cut of an accent.
ACCENT_FIXED_TONE = 90
ACCENT_FIXED_DIM_TONE = 80


def to_argb(value: str) -> int:
    return 0xFF000000 | int(value.lstrip("#"), 16)


def to_hex(argb: int) -> str:
    return "#%06x" % (argb & 0xFFFFFF)


def relative_luminance(argb: int) -> float:
    def channel(c: int) -> float:
        s = c / 255.0
        return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4

    r = channel((argb >> 16) & 0xFF)
    g = channel((argb >> 8) & 0xFF)
    b = channel(argb & 0xFF)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: int, b: int) -> float:
    la, lb = relative_luminance(a), relative_luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def main() -> int:
    seed = Hct.from_int(to_argb(SEED))
    neutral = TonalPalette.from_hue_and_chroma(seed.hue, seed.chroma)

    if to_hex(neutral.tone(seed.tone)) != SEED:
        print(f"neutral ramp does not reproduce seed {SEED}", file=sys.stderr)
        return 1

    def solve(palette, background, start, stop):
        step = 1 if stop > start else -1
        for tone in range(start, stop + step, step):
            candidate = palette.tone(tone)
            if contrast(background, candidate) >= MIN_CONTRAST:
                return candidate
        return None

    on_accents = {}
    containers = {}
    on_containers = {}
    fixed = {}
    fixed_dim = {}
    failures = []
    for name, value in ACCENTS.items():
        accent_argb = to_argb(value)
        accent = Hct.from_int(accent_argb)
        palette = TonalPalette.from_hue_and_chroma(accent.hue, accent.chroma)

        container_argb = palette.tone(ACCENT_CONTAINER_TONE)
        on_accent = solve(palette, accent_argb, ON_ACCENT_START_TONE, 0)
        on_container = solve(
            palette, container_argb, ON_ACCENT_CONTAINER_START_TONE, 100
        )

        if on_accent is None or on_container is None:
            failures.append(name)
            continue

        on_accents[name] = to_hex(on_accent)
        containers[name] = to_hex(container_argb)
        on_containers[name] = to_hex(on_container)
        fixed[name] = to_hex(palette.tone(ACCENT_FIXED_TONE))
        fixed_dim[name] = to_hex(palette.tone(ACCENT_FIXED_DIM_TONE))

    if failures:
        joined = ", ".join(sorted(failures))
        print(f"no tone reaches {MIN_CONTRAST:.1f}:1 for {joined}", file=sys.stderr)
        return 1

    lines = [
        "# AUTO-GENERATED by modules/home/common/theme/tones.py. Do not edit.",
        "# Regenerate with `nix build .#theme-tones && cp -f result modules/home/common/theme/tones.nix`.",
        "{",
        f'  seed = "{SEED}";',
        f"  hue = {seed.hue:.4f};",
        f"  chroma = {seed.chroma:.4f};",
        "",
        "  neutral = {",
    ]
    for tone in NEUTRAL_TONES:
        lines.append(f'    "{tone}" = "{to_hex(neutral.tone(tone))}";')
    lines.append("  };")

    for label, table in [
        ("onAccent", on_accents),
        ("accentContainer", containers),
        ("onAccentContainer", on_containers),
        ("accentFixed", fixed),
        ("accentFixedDim", fixed_dim),
    ]:
        lines.append("")
        lines.append(f"  {label} = {{")
        for name in sorted(table):
            lines.append(f'    {name} = "{table[name]}";')
        lines.append("  };")

    lines.append("}")

    sys.stdout.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
