{ inputs, lib, ... }:
let
  dtcg = import ./dtcg;

  inherit (dtcg) read;

  tokens = dtcg.load [
    ./tokens/dracula.tokens.json
    ./tokens/material3.tokens.json
    ./tokens/tones.tokens.json
    ./tokens/desktop.tokens.json
  ];

  inherit (tokens) desktop dracula md;

  vendor = "com.github.hakan-demirli.dotfiles";

  number =
    n:
    let
      s = builtins.toString n;
      whole = builtins.match "(-?[0-9]+)\\.?0*" s;
      fraction = builtins.match "(-?[0-9]+\\.[0-9]*[1-9])0*" s;
    in
    if whole != null then
      builtins.head whole
    else if fraction != null then
      builtins.head fraction
    else
      s;

  bezier = points: "cubic-bezier(${builtins.concatStringsSep ", " (map number points)})";

  shape = read md.sys.shape.corner;

  theme = {
    dracula = read dracula.color;
    ansi = read dracula.ansi;

    syntax = builtins.mapAttrs (
      _: role: read role // { decoration = (dtcg.extensions role).${vendor}.decoration or [ ]; }
    ) (dtcg.members dracula.syntax);

    palette = read md.sys.color // read desktop.color;

    inherit shape;
    space = read desktop.space;

    state = read md.sys.state;
    weight = read md.ref.typeface.weight;

    elevation =
      let
        levels = read md.sys.elevation;
      in
      builtins.genList (level: levels."level${toString level}") (
        builtins.length (builtins.attrNames levels)
      );

    font = {
      family = read desktop.typeface;
      scale = read md.sys.typescale;
    };

    motion = {
      duration = read md.sys.motion.duration;
      easing = read md.sys.motion.easing;

      css = builtins.mapAttrs (_: bezier) (read md.sys.motion.easing);
    };

    sizes =
      let
        component = read desktop.component;
        columns = (read desktop.grid).swayncButtonColumns;
        insets = 2 * shape.extraSmall + 4 * shape.small;
        gaps = (columns - 1) * shape.small;
      in
      component
      // {
        swayncButtonCell = (component.swayncWidth - insets - gaps) / columns;
      };
  };

  homeRoot = "modules/home/common";
  configRoot = "${homeRoot}/config";

  upperChars = lib.stringToCharacters "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  lowerChars = lib.stringToCharacters "abcdefghijklmnopqrstuvwxyz";
  kebab = builtins.replaceStrings upperChars (map (c: "-${c}") lowerChars);

  banner = "AUTO-GENERATED by modules/theme. Do not edit. Run `nix build .#theme-render && cp -rT --no-preserve=mode result modules/home/common`.";

  cssBanner = "/* ${banner} */";
  hashBanner = "# ${banner}";

  defineColors =
    attrs:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "@define-color ${kebab name} ${value};") attrs
    );

  paletteCss = ''
    ${cssBanner}

    ${defineColors theme.dracula}

    ${defineColors theme.palette}
  '';

  paletteConsumers = [
    "anyrun"
    "swaync"
    "wofi"
  ];

  prefixed =
    prefix: render: attrs:
    lib.mapAttrs' (name: value: lib.nameValuePair "${prefix}-${kebab name}" (render value)) attrs;

  tokenValues = {
    "font-brand" = theme.font.family.brand;
    "font-plain" = theme.font.family.plain;
    "font-mono" = theme.font.family.mono;
    "font-icon" = theme.font.family.icon;
    "font-symbols" = theme.font.family.symbols;
  }
  // prefixed "colour" lib.id (theme.dracula // theme.palette)
  // prefixed "ansi" lib.id theme.ansi
  // prefixed "radius" toString theme.shape
  // prefixed "space" toString theme.space
  // prefixed "text" (role: toString role.size) theme.font.scale
  // prefixed "text-line" (role: toString role.lineHeight) theme.font.scale
  // prefixed "text-weight" (role: toString role.weight) theme.font.scale
  // prefixed "weight" toString theme.weight
  // prefixed "duration" toString theme.motion.duration
  // prefixed "state" toString theme.state
  // prefixed "easing" lib.id theme.motion.css
  // prefixed "size" toString theme.sizes;

  substitute = builtins.replaceStrings (map (name: "{{${name}}}") (lib.attrNames tokenValues)) (
    lib.attrValues tokenValues
  );

  template =
    banner: name: "${banner}\n\n${substitute (builtins.readFile (./templates + "/${name}"))}";

  kittyTheme =
    let
      pair = key: value: "${key} ${value}";
      inherit (theme) ansi;
      indexed = [
        ansi.black
        ansi.red
        ansi.green
        ansi.yellow
        ansi.blue
        ansi.magenta
        ansi.cyan
        ansi.white
        ansi.brightBlack
        ansi.brightRed
        ansi.brightGreen
        ansi.brightYellow
        ansi.brightBlue
        ansi.brightMagenta
        ansi.brightCyan
        ansi.brightWhite
      ];
    in
    ''
      ${hashBanner}

      ${pair "foreground" theme.dracula.foreground}
      ${pair "background" theme.dracula.background}
      ${pair "selection_foreground" ansi.brightWhite}
      ${pair "selection_background" theme.dracula.selection}

      ${pair "url_color" theme.dracula.cyan}

      ${lib.concatStringsSep "\n" (lib.imap0 (i: value: pair "color${toString i}" value) indexed)}

      ${pair "cursor" theme.dracula.foreground}
      cursor_text_color background

      ${pair "active_tab_foreground" theme.dracula.background}
      ${pair "active_tab_background" theme.dracula.foreground}
      ${pair "inactive_tab_foreground" theme.dracula.background}
      ${pair "inactive_tab_background" theme.dracula.comment}

      ${pair "mark1_foreground" theme.dracula.background}
      ${pair "mark1_background" theme.dracula.red}
    '';

  files =
    lib.listToAttrs (
      lib.concatMap (app: [
        (lib.nameValuePair "config/${app}/colors.css" paletteCss)
        (lib.nameValuePair "config/${app}/style.css" (template cssBanner "${app}.css.in"))
      ]) paletteConsumers
    )
    // {
      "config/kitty/dracula.conf" = kittyTheme;
      "config/tofi/config" = template hashBanner "tofi.config.in";
      "config/hypr/hyprlock.conf" = template hashBanner "hyprlock.conf.in";
      "config/quickshell/Theme.qml" = template cssBanner "quickshell.Theme.qml.in";

      "theme.nix" = "${hashBanner}\n\n${dtcg.emit theme}\n";
    };

  renderedPaths = lib.attrNames files;

  diagrams =
    let
      graph = (dtcg.load [ ./tokens/diagrams.tokens.json ]).diagrams;
      typeface = read graph.typeface;
      fleet = read graph.fleet;
    in
    {
      fontFamily = builtins.concatStringsSep ", " typeface.stack;
      fontFamilyGraphviz = typeface.graphviz;

      fontSize = read graph.fontSize;
      stroke = read graph.stroke;
      strokeWidthPt = read graph.strokeWidthPt;
      radius = read graph.radius;

      palette = read graph.color;

      fleetPalette = builtins.genList (index: fleet.${toString index}) (
        builtins.length (builtins.attrNames fleet)
      );

      fleetSolo = read graph.fleetSolo;
    };

  diagramsPath = "modules/diagrams/theme.nix";
  tonesPath = "modules/theme/tokens/tones.tokens.json";

  diagramsBanner = "# AUTO-GENERATED by modules/theme. Do not edit. Run `nix build .#diagrams-theme && cp -f --no-preserve=mode result ${diagramsPath}`.";

  definedColours = lib.naturalSort (
    map kebab (lib.attrNames theme.dracula ++ lib.attrNames theme.palette)
  );

  cssAtRules = [
    "charset"
    "import"
    "keyframes"
    "media"
    "supports"
  ];

  paletteExempt = [
    "btop/themes/*.theme"
    "QtProject/qtcreator/styles/*.xml"
    "yazi/theme.toml"
  ];

  cssNamedColours = [
    "aqua"
    "black"
    "blue"
    "cyan"
    "fuchsia"
    "gray"
    "green"
    "grey"
    "lime"
    "magenta"
    "maroon"
    "navy"
    "olive"
    "orange"
    "pink"
    "purple"
    "red"
    "silver"
    "teal"
    "white"
    "yellow"
  ];
in
{
  perSystem =
    { pkgs, ... }:
    let
      rendered =
        pkgs.runCommand "theme-render"
          {
            nativeBuildInputs = [
              pkgs.nixfmt
              pkgs.prettier
              pkgs.qt6.qtdeclarative
            ];
          }
          ''
            mkdir -p "$out"
            ${lib.concatStringsSep "\n" (
              lib.mapAttrsToList (path: text: ''
                mkdir -p "$out/$(dirname ${lib.escapeShellArg path})"
                cp ${pkgs.writeText (baseNameOf path) text} "$out/${path}"
              '') files
            )}
            chmod -R u+w "$out"

            if grep -rn '{{' "$out"; then
              echo "theme-render: unsubstituted template token remains." >&2
              exit 1
            fi

            find "$out" -name '*.css' -exec prettier --write --parser css {} + > /dev/null
            find "$out" -name '*.qml' -exec qmlformat --inplace --ignore-settings --indent-width 4 {} +
            find "$out" -name '*.nix' -exec nixfmt {} +
          '';

      diagramsTheme = pkgs.runCommand "diagrams-theme" { nativeBuildInputs = [ pkgs.nixfmt ]; } ''
        cp ${pkgs.writeText "theme.nix" "${diagramsBanner}\n\n${dtcg.emit diagrams}\n"} theme.nix
        chmod u+w theme.nix
        nixfmt theme.nix
        cp theme.nix "$out"
      '';

      tones =
        pkgs.runCommand "theme-tones"
          {
            nativeBuildInputs = [
              (pkgs.python3.withPackages (ps: [ ps.materialyoucolor ]))
              pkgs.prettier
            ];
          }
          ''
            python3 ${./tones.py} ${./tokens/dracula.tokens.json} > tones.tokens.json
            prettier --write --parser json tones.tokens.json > /dev/null
            cp tones.tokens.json "$out"
          '';
    in
    {
      packages = {
        theme-render = rendered;
        diagrams-theme = diagramsTheme;
        theme-tones = tones;
      };

      checks = {
        diagrams-drift =
          pkgs.runCommand "check-diagrams-drift"
            {
              src = inputs.self;
              generated = diagramsTheme;
            }
            ''
              if ! diff -u "$src/${diagramsPath}" "$generated"; then
                echo "diagrams-drift: ${diagramsPath} differs from generated output" >&2
                echo "Regenerate with:" >&2
                echo "  nix build .#diagrams-theme" >&2
                echo "  cp -f --no-preserve=mode result ${diagramsPath}" >&2
                exit 1
              fi

              touch "$out"
            '';

        theme-tones-drift =
          pkgs.runCommand "check-theme-tones-drift"
            {
              src = inputs.self;
              generated = tones;
            }
            ''
              if ! diff -u "$src/${tonesPath}" "$generated"; then
                echo "theme-tones-drift: ${tonesPath} differs from generated output" >&2
                echo "Regenerate with:" >&2
                echo "  nix build .#theme-tones" >&2
                echo "  cp -f --no-preserve=mode result ${tonesPath}" >&2
                exit 1
              fi

              touch "$out"
            '';

        dtcg-conformance =
          pkgs.runCommand "check-dtcg-conformance"
            {
              src = inputs.self;
              nativeBuildInputs = [
                (pkgs.python3.withPackages (ps: [
                  ps.jsonschema
                  ps.referencing
                ]))
              ];
            }
            ''
              mapfile -t files < <(find "$src" -name '*.tokens.json' | sort)

              if [ "''${#files[@]}" -eq 0 ]; then
                echo "dtcg-conformance: the repository holds no token files, so the check proves nothing." >&2
                exit 1
              fi

              printf 'checking %s\n' "''${files[@]#"$src/"}"
              python3 ${./dtcg/validate.py} ${./dtcg/schema/2025.10} "''${files[@]}"

              touch "$out"
            '';

        theme-drift =
          pkgs.runCommand "check-theme-drift"
            {
              src = inputs.self;
              inherit rendered;
            }
            ''
              failed=0

              for path in ${lib.escapeShellArgs renderedPaths}; do
                committed="$src/${homeRoot}/$path"
                generated="$rendered/$path"

                if [ ! -e "$committed" ]; then
                  echo "theme-drift: missing committed file ${homeRoot}/$path" >&2
                  failed=1
                  continue
                fi

                if ! diff -u "$committed" "$generated"; then
                  echo "theme-drift: ${homeRoot}/$path differs from generated output" >&2
                  failed=1
                fi
              done

              if [ "$failed" -ne 0 ]; then
                echo "Regenerate with:" >&2
                echo "  nix build .#theme-render" >&2
                echo "  cp -rT --no-preserve=mode result ${homeRoot}" >&2
                exit 1
              fi

              touch "$out"
            '';

        theme-coverage =
          if pkgs.stdenv.hostPlatform.isLinux then
            pkgs.runCommand "check-theme-coverage"
              {
                src = inputs.self;
                nativeBuildInputs = [ pkgs.python3 ];
              }
              ''
                python3 ${./coverage.py} \
                  ${pkgs.swaynotificationcenter}/etc/xdg/swaync/style.css \
                  "$src/${configRoot}/swaync/style.css"

                touch "$out"
              ''
          else
            pkgs.runCommand "check-theme-coverage" { } ''
              touch "$out"
            '';

        theme-fonts =
          pkgs.runCommand "check-theme-fonts"
            {
              nativeBuildInputs = [
                pkgs.fontconfig
                pkgs.ripgrep
              ];
              fonts = pkgs.symlinkJoin {
                name = "theme-fonts";
                paths = [
                  pkgs.roboto
                  pkgs.material-symbols
                  pkgs.nerd-fonts.jetbrains-mono
                  pkgs.nerd-fonts.symbols-only
                ];
              };
            }
            ''
              failed=0

              fc-scan --format '%{family}|%{style}\n' "$fonts/share/fonts" > faces.txt

              for family in ${lib.escapeShellArgs (lib.unique (lib.attrValues theme.font.family))}; do
                awk -F'|' -v want="$family" '
                  {
                    n = split($1, names, ",")
                    for (i = 1; i <= n; i++) {
                      if (names[i] == want) { print $2; next }
                    }
                  }
                ' faces.txt > styles.txt

                if [ ! -s styles.txt ]; then
                  echo "theme-fonts: family '$family' is not provided by any declared package." >&2
                  failed=1
                  continue
                fi

                if awk -F',' '
                  {
                    italic = 0; regular = 0
                    for (i = 1; i <= NF; i++) {
                      if ($i ~ /Italic/) italic = 1
                      if ($i == "Regular") regular = 1
                    }
                    if (italic && regular) { print "  offending style: " $0; found = 1 }
                  }
                  END { exit !found }
                ' styles.txt >&2; then
                  echo "theme-fonts: family '$family' has an italic face advertising the Regular style." >&2
                  failed=1
                fi
              done

              if [ "$failed" -ne 0 ]; then
                exit 1
              fi

              touch "$out"
            '';

        theme-tokens =
          pkgs.runCommand "check-theme-tokens"
            {
              src = inputs.self;
              nativeBuildInputs = [ pkgs.ripgrep ];
            }
            ''
                  failed=0
                  printf '%s\n' ${lib.escapeShellArgs definedColours} | sort -u > defined.txt

                  for app in ${lib.escapeShellArgs paletteConsumers}; do
                    style="$src/${configRoot}/$app/style.css"
                    [ -e "$style" ] || continue

                    if rg -n '#[0-9a-fA-F]{3,8}\b' "$style"; then
                      echo "theme-tokens: $app/style.css contains a literal hex colour." >&2
                      failed=1
                    fi

                    if rg -n 'rgba?\([0-9]' "$style"; then
                      echo "theme-tokens: $app/style.css contains a literal rgb colour." >&2
                      failed=1
                    fi

              template="$src/modules/nix/theme/templates/$app.css.in"

              if [ -e "$template" ] && rg -n 'font-size:\s*[0-9.]+(px|rem|pt|em)' "$template"; then
                echo "theme-tokens: $app.css.in has a font size outside the type scale." >&2
                failed=1
              fi

              if [ -e "$template" ] && rg -n --pcre2 \
                '(?:padding|margin)(?:-(?:top|bottom|left|right))?:[^;]*(?<![.\d])-?(?:[3-9]|\d\d+)px' \
                "$template"; then
                echo "theme-tokens: $app.css.in has spacing outside the 4dp grid." >&2
                failed=1
              fi

              if [ -e "$template" ] && rg -n --pcre2 \
                'border(?:-(?:top|bottom)-(?:left|right))?-radius:[^;]*(?<![.\d])[1-9]\d*px' \
                "$template"; then
                echo "theme-tokens: $app.css.in has a corner radius outside the shape scale." >&2
                failed=1
              fi

                    if rg -nP ${lib.escapeShellArg "(?<![-\\w@\"])(${lib.concatStringsSep "|" cssNamedColours})(?![-\\w])"} "$style"; then
                      echo "theme-tokens: $app/style.css contains a CSS named colour." >&2
                      failed=1
                    fi

                    rg -oN '@[a-zA-Z][a-zA-Z0-9-]*' "$style" \
                      | sed 's/^@//' \
                      | sort -u \
                      | rg -vx ${lib.escapeShellArgs [ (lib.concatStringsSep "|" cssAtRules) ]} \
                      > used.txt || true

                    if comm -13 defined.txt used.txt | rg .; then
                      echo "theme-tokens: $app/style.css references colours absent from $app/colors.css." >&2
                      failed=1
                    fi
                  done

                  printf '%s\n' ${
                    lib.escapeShellArgs (
                      lib.naturalSort (lib.attrValues (theme.dracula // theme.palette // theme.ansi))
                    )
                  } | tr 'A-F' 'a-f' | sort -u > palette.txt
                  tr -d '#' < palette.txt | sort -u > palette-bare.txt

                  for config in "$src/${configRoot}"/hypr/*.lua "$src/${configRoot}"/hypr/*.conf; do
                    [ -e "$config" ] || continue

                    rg -oN --pcre2 '(?<=rgba?\()[0-9a-fA-F]{6}' "$config" | sort -u > hyprcolours.txt || true

                    if comm -13 palette-bare.txt hyprcolours.txt | rg .; then
                      echo "theme-tokens: $(basename "$config") uses a colour outside the palette." >&2
                      failed=1
                    fi
                  done

              printf '%s\n' ${lib.escapeShellArgs (lib.unique (lib.attrValues theme.font.family))} | sort -u > families.txt

              rg -oIN --pcre2 \
                '(?:^\s*font_family\s*=?\s*|^\s*font\s*=\s*|font-family:\s*)\K[^;{}]+' \
                "$src/${configRoot}" \
                | tr ',' '\n' \
                | sed 's/^[[:space:]"]*//; s/[[:space:]";]*$//' \
                | rg -v '^$' \
                | sort -u > declared-families.txt || true

              if comm -13 families.txt declared-families.txt | rg .; then
                echo "theme-tokens: the families above are not in modules/home/common/theme." >&2
                failed=1
              fi

                if rg -n --pcre2 "(?:foreground|background)='(?!#)" "$src/${configRoot}"; then
                  echo "theme-tokens: Pango markup must use palette hex, not a colour name." >&2
                  failed=1
                fi

                  while IFS= read -r config; do
                    case "''${config#"$src/${configRoot}/"}" in
                      ${lib.concatMapStringsSep "|" (glob: "${glob}") paletteExempt})
                        continue
                        ;;
                    esac

                    rg -oIN --pcre2 '#(?i)[0-9a-f]{6}\b' "$config" \
                      | tr 'A-F' 'a-f' | sort -u > filecolours.txt || true

                    if comm -13 palette.txt filecolours.txt | rg .; then
                      echo "theme-tokens: ''${config#"$src/${configRoot}/"} uses colours outside the palette." >&2
                      failed=1
                    fi
                  done < <(find "$src/${configRoot}" -type f)

                  if [ "$failed" -ne 0 ]; then
                    echo "Colours must come from modules/home/common/theme." >&2
                    exit 1
                  fi

                  touch "$out"
            '';
      };
    };
}
