import json
import sys
from pathlib import Path

from materialyoucolor.hct import Hct
from materialyoucolor.palettes.tonal_palette import TonalPalette

SCHEMA = "https://www.designtokens.org/schemas/2025.10/format.json"

SEED = "background"

ACCENTS = ["cyan", "green", "orange", "pink", "purple", "red", "yellow"]

NEUTRAL_TONES = [0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 60, 80, 90]

ON_ACCENT_START_TONE = 20
ACCENT_CONTAINER_TONE = 30
ON_ACCENT_CONTAINER_START_TONE = 90
MIN_CONTRAST = 4.5

ACCENT_FIXED_TONE = 90
ACCENT_FIXED_DIM_TONE = 80


def to_argb(components: list[float]) -> int:
    value = 0
    for component in components:
        value = (value << 8) | round(component * 255)
    return 0xFF000000 | value


def to_hex(argb: int) -> str:
    return "#%06x" % (argb & 0xFFFFFF)


def token(argb: int) -> dict:
    return {
        "$value": {
            "colorSpace": "srgb",
            "components": [((argb >> shift) & 0xFF) / 255 for shift in (16, 8, 0)],
            "hex": to_hex(argb),
        }
    }


def relative_luminance(argb: int) -> float:
    def channel(c: int) -> float:
        s = c / 255.0
        return s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4

    r = channel((argb >> 16) & 0xFF)
    g = channel((argb >> 8) & 0xFF)
    b = channel(argb & 0xFF)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a: int, b: int) -> float:
    la, lb = relative_luminance(a), relative_luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def sources(path: Path) -> dict[str, int]:
    document = json.loads(path.read_text())
    group = document["dracula"]["color"]
    return {
        name: to_argb(entry["$value"]["components"])
        for name, entry in group.items()
        if not name.startswith("$")
    }


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print("usage: tones.py DRACULA_TOKENS", file=sys.stderr)
        return 2

    dracula = sources(Path(argv[1]))

    missing = [name for name in [SEED, *ACCENTS] if name not in dracula]
    if missing:
        print(f"tones: {argv[1]} names no {', '.join(missing)}", file=sys.stderr)
        return 1

    seed = Hct.from_int(dracula[SEED])
    neutral = TonalPalette.from_hue_and_chroma(seed.hue, seed.chroma)

    if neutral.tone(seed.tone) != dracula[SEED]:
        print(
            f"tones: the neutral ramp does not reproduce {to_hex(dracula[SEED])}",
            file=sys.stderr,
        )
        return 1

    def solve(palette, background, start, stop):
        step = 1 if stop > start else -1
        for tone in range(start, stop + step, step):
            candidate = palette.tone(tone)
            if contrast(background, candidate) >= MIN_CONTRAST:
                return candidate
        return None

    groups = {
        "onAccent": {},
        "accentContainer": {},
        "onAccentContainer": {},
        "accentFixed": {},
        "accentFixedDim": {},
    }
    failures = []
    for name in ACCENTS:
        accent_argb = dracula[name]
        accent = Hct.from_int(accent_argb)
        palette = TonalPalette.from_hue_and_chroma(accent.hue, accent.chroma)

        container_argb = palette.tone(ACCENT_CONTAINER_TONE)
        on_accent = solve(palette, accent_argb, ON_ACCENT_START_TONE, 0)
        on_container = solve(
            palette, container_argb, ON_ACCENT_CONTAINER_START_TONE, 100
        )

        if on_accent is None or on_container is None:
            failures.append(name)
            continue

        groups["onAccent"][name] = token(on_accent)
        groups["accentContainer"][name] = token(container_argb)
        groups["onAccentContainer"][name] = token(on_container)
        groups["accentFixed"][name] = token(palette.tone(ACCENT_FIXED_TONE))
        groups["accentFixedDim"][name] = token(palette.tone(ACCENT_FIXED_DIM_TONE))

    if failures:
        joined = ", ".join(sorted(failures))
        print(
            f"tones: no tone reaches {MIN_CONTRAST:.1f}:1 for {joined}", file=sys.stderr
        )
        return 1

    document = {
        "$schema": SCHEMA,
        "tones": {
            "$description": "AUTO-GENERATED by modules/theme. Do not edit. Run `nix build .#theme-tones && cp -f --no-preserve=mode result modules/theme/tokens/tones.tokens.json`.",
            "$type": "color",
            "neutral": {str(tone): token(neutral.tone(tone)) for tone in NEUTRAL_TONES},
            **groups,
        },
    }

    sys.stdout.write(json.dumps(document, indent=2) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
