#pragma once

#define SPLIT_HAND_PIN GP10
#define SPLIT_HAND_PIN_LOW_IS_LEFT

#define TAPPING_TERM 200
#define QUICK_TAP_TERM 0

#define MOUSEKEY_INTERVAL 16
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_MAX_SPEED 7
#define MOUSEKEY_WHEEL_DELAY 0
