monitor = ,disable

env = PATH,/run/wrappers/bin:/home/emre/.nix-profile/bin:/etc/profiles/per-user/emre/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/home/emre/.local/bin
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = MOZ_ENABLE_WAYLAND,1
env = NIXOS_OZONE_WL,1

input {
    kb_layout = us
    follow_mouse = 1
    repeat_rate = 60
    repeat_delay = 200
}

general {
    border_size = 2
    gaps_in = 3
    gaps_out = 3
    layout = dwindle
}

dwindle {
    preserve_split = true
}

misc {
    disable_hyprland_logo = true
    mouse_move_enables_dpms = false
    key_press_enables_dpms = false
}

$mainMod  = SUPER
$launcher = pkill tofi || tofi-drun --drun-launch=true
$locker   = hyprlock

bindr = SUPER, SUPER_L, exec, $launcher
bindr = SUPER, SUPER_R, exec, $launcher

bind = ALT,      N,      exec, todo_my
bind = ALT,      Z,      exec, plan_my
bind = $mainMod, M,      exec, player_my

bind = ALT, Tab,    workspace, previous
bind = ALT, M,      workspace, 1
bind = ALT, COMMA,  workspace, 2
bind = ALT, PERIOD, workspace, 3
bind = ALT, SLASH,  workspace, 4

bind = $mainMod, B,   exec, pkill waybar || waybar
bind = $mainMod, Tab, workspace, previous

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

binde = $mainMod CTRL, H, resizeactive, -20 0
binde = $mainMod CTRL, J, resizeactive,  0 20
binde = $mainMod CTRL, K, resizeactive,  0 -20
binde = $mainMod CTRL, L, resizeactive,  20 0

bind = $mainMod, Q,      killactive
bind = $mainMod, F,      fullscreen
bind = $mainMod, escape, exec, $locker
bind = $mainMod, S,      layoutmsg, togglesplit
bind = $mainMod, E,      togglefloating
bind = $mainMod, R,      pin

bind = ,         Print, exec, pkill -9 wayscriber || wayscriber -a
bind = $mainMod SHIFT, S, exec, pkill -9 wayscriber || wayscriber -a
bind = $mainMod,       Y, exec, pkill -9 wayscriber || wayscriber -a

bind = $mainMod CTRL, F4, exit

bind = $mainMod CTRL, 1, movetoworkspace, 1
bind = $mainMod CTRL, 2, movetoworkspace, 2
bind = $mainMod CTRL, 3, movetoworkspace, 3
bind = $mainMod CTRL, 4, movetoworkspace, 4
bind = $mainMod CTRL, 5, movetoworkspace, 5
bind = $mainMod CTRL, 6, movetoworkspace, 6
bind = $mainMod CTRL, 7, movetoworkspace, 7
bind = $mainMod CTRL, 8, movetoworkspace, 8
bind = $mainMod CTRL, 9, movetoworkspace, 9
bind = $mainMod CTRL, 0, movetoworkspace, 10

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind  = $mainMod, mouse_down, workspace, e-1
bind  = $mainMod, mouse_up,   workspace, e+1

exec-once = dbus-update-activation-environment --systemd --all
