default_mode: insert

# virtual_modifiers:
#   - KEY_F19
# modmap:
#   - name: deflt
#     remap:
#       KEY_SPACE:
#         held: KEY_F19
#         alone: KEY_SPACE
#         alone_timeout_millis: 1550 

keymap:
  - name: Default
    remap:
      KEY_GRAVE: reserved 
      KEY_RIGHTBRACE: reserved
      KEY_BACKSLASH: reserved
      KEY_LEFTBRACE: KEY_BACKSPACE
      Shift-KEY_LEFTBRACE: KEY_DELETE
      Alt-Shift-KEY_LEFTBRACE: Shift-KEY_MINUS # underscore
      KEY_BACKSPACE: reserved
      KEY_ENTER: reserved
      KEY_APOSTROPHE: KEY_ENTER

      # Right Hand
      Shift-Alt-y: KEY_APOSTROPHE
      Shift-Alt-u: Shift-KEY_LEFTBRACE # curly
      Shift-Alt-i: Shift-KEY_RIGHTBRACE # curly
      Shift-Alt-o: Shift-KEY_4 # dollar
      Shift-Alt-p: KEY_PASTE

      Shift-Alt-h: KEY_HOME
      Shift-Alt-j: KEY_KPLEFTPAREN
      Shift-Alt-k: KEY_KPRIGHTPAREN
      Shift-Alt-l: KEY_END
      Shift-Alt-KEY_SEMICOLON: reserved

      Shift-Alt-n: Shift-KEY_APOSTROPHE
      Shift-Alt-m: KEY_LEFTBRACE
      Shift-Alt-comma: KEY_RIGHTBRACE
      Shift-Alt-dot: reserved
      Shift-Alt-slash: reserved

      # Alt-y: reserved # tmux prefix
      # Alt-u: tmux tab 1
      # Alt-i: tmux tab 2
      # Alt-o: tmux tab 3
      # Alt-p: tmux tab 4
      Alt-KEY_SPACE: KEY_SPACE

      Alt-h: KEY_LEFT
      Alt-j: KEY_DOWN
      Alt-k: KEY_UP
      Alt-l: KEY_RIGHT
      Alt-KEY_SEMICOLON: reserved

      Alt-n: reserved
      # Alt-m: workspace 1
      # Alt-comma: workspace 2
      # Alt-dot: workspace 3
      # Alt-slash: workspace 4


      # Left Hand
      Shift-Alt-q: reserved
      Shift-Alt-w: Shift-KEY_7 # ampersand 
      Shift-Alt-e: Shift-KEY_8 # star
      Shift-Alt-r: Shift-KEY_6 # caret
      Shift-Alt-t: Shift-KEY_2 # at

      Shift-Alt-a: Shift-KEY_1 # exclamation mark
      Shift-Alt-s: KEY_MINUS 
      Shift-Alt-d: Shift-KEY_EQUAL # plus
      Shift-Alt-f: KEY_EQUAL
      Shift-Alt-g: Shift-KEY_3 # pound

      Shift-Alt-z: KEY_BACKSLASH
      Shift-Alt-x: Shift-KEY_GRAVE # tilda
      Shift-Alt-c: KEY_GRAVE
      Shift-Alt-v: Shift-KEY_5 # percent
      Shift-Alt-b: Shift-KEY_BACKSLASH # pipe

      # Alt-q: quit tab
      Alt-w: KEY_7
      Alt-e: KEY_8
      Alt-r: KEY_9
      Alt-t: KEY_0

      # Alt-a: open terminal
      Alt-s: KEY_4
      Alt-d: KEY_5
      Alt-f: KEY_6
      # Alt-g: reserved # tmux harpoon add key

      # Alt-z: open browser
      Alt-x: KEY_1
      Alt-c: KEY_2
      Alt-v: KEY_3
      # Alt-b: toggle waybar


      KEY_1: reserved
      KEY_2: reserved
      KEY_3: reserved
      KEY_4: reserved
      KEY_5: reserved
      KEY_6: reserved
      KEY_7: reserved
      KEY_8: reserved
      KEY_9: reserved
      KEY_0: reserved
      KEY_MINUS: reserved
      KEY_EQUAL: reserved

  - name: helix
    application:
      only: helix
    remap:
      KEY_BACKSPACE: reserved

  - name: Xschem
    application:
      only: Xschem
    remap:
      Alt-1: insert

  - mode: command
    application:
      only: Code
    remap:
      CapsLock: [
          esc,
          { set_mode: normal },
        ]
      Esc:  [
          { set_mode: normal },
        ]
      Enter: [Enter, { set_mode: normal }]

  - mode: command_search
    application:
      only: Code
    remap:
      CapsLock: [
          esc,
          { set_mode: normal },
        ]
      Esc:  [
          { set_mode: normal },
        ]
      Enter: [Ctrl-Down,Enter,Ctrl-b, { set_mode: normal }]

  - mode: insert
    application:
      only: Code
    remap:
      CapsLock: [
          esc,
          launch:
            ["python","/mnt/second/rep/dotfiles/scripts/python/changeVscodeCursor.py","--style",  "block"],
          { set_mode: normal },
        ]
      Esc:  [
          launch:
            ["python","/mnt/second/rep/dotfiles/scripts/python/changeVscodeCursor.py","--style",  "block"],
          { set_mode: normal },
        ]

  - mode: normal
    application:
      only: Code
    remap:
      i:  [
          launch:
            ["python","/mnt/second/rep/dotfiles/scripts/python/changeVscodeCursor.py", "--style", "line"],
          { set_mode: insert },
        ]
      c:  [
          delete,
          launch:
            ["python","/mnt/second/rep/dotfiles/scripts/python/changeVscodeCursor.py", "--style", "line"],
          { set_mode: insert },
        ]
      Ctrl-c: Ctrl-c
      a:  [
        Right,
        launch:
          ["python","/mnt/second/rep/dotfiles/scripts/python/changeVscodeCursor.py", "--style", "line"],
        { set_mode: insert },
      ]
      o:  [
          C-enter,
          launch:
            ["python","/mnt/second/rep/dotfiles/scripts/python/changeVscodeCursor.py", "--style", "line"],
          { set_mode: insert },
        ]
      h: Left
      Ctrl-h: Ctrl-h
      j: Down
      k: Up
      Ctrl-k: Ctrl-k
      l: Right
      e: reserved
      r: reserved
      q: reserved
      z: reserved
      v: reserved
      x: reserved
      KEY_ENTER: reserved
      KEY_BACKSPACE: reserved
      # x: [Home,Shift-end]
      Ctrl-x: Ctrl-x
      w: [Ctrl-Shift-Right]
      Ctrl-w: Ctrl-w
      b: [Ctrl-Shift-Left]
      Ctrl-b: Ctrl-b
      # 0: Home
      # Shift-KEY_4: End
      u: C-z
      Ctrl-u: Ctrl-u
      y: C-c
      p: C-v
      d: delete
      Shift-d: KEY_BACKSPACE
      f: Alt-m
      Ctrl-d: Ctrl-d
      CapsLock: Esc
      slash: [C-f, { set_mode: command }]
      Ctrl-slash: Ctrl-slash # comment selected line
      Shift-slash: reserved
      Shift-dot: C-KEY_RIGHTBRACE
      Shift-comma: C-KEY_LEFTBRACE
      space:
         remap:
           f: [C-p, { set_mode: command}]
           g: [Ctrl-Shift-f, { set_mode: command_search}]
           t: [Ctrl-Shift-KEY_GRAVE, { set_mode: insert}]
      g:
         remap:
           g: C-Home
           e: C-End
           p: C-KEY_PAGEUP
           n: C-KEY_PAGEDOWN
           d: KEY_F12
           r: Shift-KEY_F12
           h: Home
           l: End
      KEY_SEMICOLON:
         remap:
           w: C-s


# I found the following workflow to be fairly painless:
#   Select text region with mouse or keyboard.
#   Ctrl+H to toggle find and replace
#   Alt+L to toggle find in selection
#   Ctrl+Alt+Enter to replace all (or enter to replace individually)


# {KEY_ESC, KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0, KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE, KEY_TAB, KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P, KEY_LEFTBRACE, KEY_RIGHTBRACE, KEY_ENTER, KEY_LEFTCTRL, KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L, KEY_SEMICOLON, KEY_APOSTROPHE, KEY_GRAVE, KEY_LEFTSHIFT, KEY_BACKSLASH, KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M, KEY_COMMA, KEY_DOT, KEY_SLASH, KEY_RIGHTSHIFT, KEY_KPASTERISK, KEY_LEFTALT, KEY_SPACE, KEY_CAPSLOCK, KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10, KEY_NUMLOCK, KEY_SCROLLLOCK, KEY_KP7, KEY_KP8, KEY_KP9, KEY_KPMINUS, KEY_KP4, KEY_KP5, KEY_KP6, KEY_KPPLUS, KEY_KP1, KEY_KP2, KEY_KP3, KEY_KP0, KEY_KPDOT, KEY_ZENKAKUHANKAKU, KEY_102ND, KEY_F11, KEY_F12, KEY_RO, KEY_KATAKANA, KEY_HIRAGANA, KEY_HENKAN, KEY_KATAKANAHIRAGANA, KEY_MUHENKAN, KEY_KPJPCOMMA, KEY_KPENTER, KEY_RIGHTCTRL, KEY_KPSLASH, KEY_SYSRQ, KEY_RIGHTALT, KEY_HOME, KEY_UP, KEY_PAGEUP, KEY_LEFT, KEY_RIGHT, KEY_END, KEY_DOWN, KEY_PAGEDOWN, KEY_INSERT, KEY_DELETE, KEY_MUTE, KEY_VOLUMEDOWN, KEY_VOLUMEUP, KEY_POWER, KEY_KPEQUAL, KEY_PAUSE, KEY_SCALE, KEY_KPCOMMA, KEY_HANGEUL, KEY_HANJA, KEY_YEN, KEY_LEFTMETA, KEY_RIGHTMETA, KEY_COMPOSE, KEY_STOP, KEY_AGAIN, KEY_PROPS, KEY_UNDO, KEY_FRONT, KEY_COPY, KEY_OPEN, KEY_PASTE, KEY_FIND, KEY_CUT, KEY_HELP, KEY_MENU, KEY_CALC, KEY_SLEEP, KEY_WAKEUP, KEY_FILE, KEY_WWW, KEY_COFFEE, KEY_MAIL, KEY_BOOKMARKS, KEY_BACK, KEY_FORWARD, KEY_EJECTCD, KEY_NEXTSONG, KEY_PLAYPAUSE, KEY_PREVIOUSSONG, KEY_STOPCD, KEY_RECORD, KEY_REWIND, KEY_PHONE, KEY_CONFIG, KEY_HOMEPAGE, KEY_REFRESH, KEY_EXIT, KEY_EDIT, KEY_SCROLLUP, KEY_SCROLLDOWN, KEY_KPLEFTPAREN, KEY_KPRIGHTPAREN, KEY_NEW, KEY_REDO, KEY_F13, KEY_F14, KEY_F15, KEY_F16, KEY_F17, KEY_F18, KEY_F19, KEY_F20, KEY_F21, KEY_F22, KEY_F23, KEY_F24, KEY_DASHBOARD, KEY_CLOSE, KEY_PLAY, KEY_FASTFORWARD, KEY_BASSBOOST, KEY_PRINT, KEY_CAMERA, KEY_CHAT, KEY_SEARCH, KEY_FINANCE, KEY_CANCEL, KEY_BRIGHTNESSDOWN, KEY_BRIGHTNESSUP, KEY_KBDILLUMTOGGLE, KEY_KBDILLUMDOWN, KEY_KBDILLUMUP, KEY_SEND, KEY_REPLY, KEY_FORWARDMAIL, KEY_SAVE, KEY_DOCUMENTS, KEY_UNKNOWN, KEY_VIDEO_NEXT, KEY_BRIGHTNESS_AUTO, BTN_0, BTN_LEFT, BTN_RIGHT, BTN_MIDDLE, BTN_SIDE, BTN_EXTRA, BTN_FORWARD, BTN_BACK, BTN_TASK, unknown key: 280, unknown key: 281, unknown key: 282, unknown key: 283, unknown key: 284, unknown key: 285, unknown key: 286, unknown key: 287, KEY_SELECT, KEY_GOTO, KEY_INFO, KEY_PROGRAM, KEY_PVR, KEY_SUBTITLE, KEY_ZOOM, KEY_KEYBOARD, KEY_SCREEN, KEY_PC, KEY_TV, KEY_TV2, KEY_VCR, KEY_VCR2, KEY_SAT, KEY_CD, KEY_TAPE, KEY_TUNER, KEY_PLAYER, KEY_DVD, KEY_AUDIO, KEY_VIDEO, KEY_MEMO, KEY_CALENDAR, KEY_RED, KEY_GREEN, KEY_YELLOW, KEY_BLUE, KEY_CHANNELUP, KEY_CHANNELDOWN, KEY_LAST, KEY_NEXT, KEY_RESTART, KEY_SLOW, KEY_SHUFFLE, KEY_PREVIOUS, KEY_VIDEOPHONE, KEY_GAMES, KEY_ZOOMIN, KEY_ZOOMOUT, KEY_ZOOMRESET, KEY_WORDPROCESSOR, KEY_EDITOR, KEY_SPREADSHEET, KEY_GRAPHICSEDITOR, KEY_PRESENTATION, KEY_DATABASE, KEY_NEWS, KEY_VOICEMAIL, KEY_ADDRESSBOOK, KEY_MESSENGER, KEY_DISPLAYTOGGLE, KEY_SPELLCHECK, KEY_LOGOFF, KEY_MEDIA_REPEAT, KEY_IMAGES, KEY_BUTTONCONFIG, KEY_TASKMANAGER, KEY_JOURNAL, KEY_CONTROLPANEL, KEY_APPSELECT, KEY_SCREENSAVER, KEY_VOICECOMMAND, KEY_ASSISTANT, KEY_KBD_LAYOUT_NEXT, unknown key: 585, unknown key: 586, KEY_BRIGHTNESS_MIN, KEY_BRIGHTNESS_MAX, KEY_KBDINPUTASSIST_PREV, KEY_KBDINPUTASSIST_NEXT, KEY_KBDINPUTASSIST_PREVGROUP, KEY_KBDINPUTASSIST_NEXTGROUP, KEY_KBDINPUTASSIST_ACCEPT, KEY_KBDINPUTASSIST_CANCEL}
