-- Generated by nwg-displays on 2024-11-02 at 17:42:28.
-- After switching to Lua, update these manually or via hyprctl.

hl.monitor({ output = "desc:Samsung Display Corp. 0x41AA",                               mode = "2880x1800@120.0", position = "0x0",    scale = 1.5 })
hl.monitor({ output = "desc:Chimei Innolux Corporation 0x1521",                          mode = "1920x1080@144.0", position = "0x1080", scale = 1 })
hl.monitor({ output = "desc:Samsung Electric Company LF24T450F HK7W202584",              mode = "1920x1080@74.97", position = "0x0",    scale = 1 })
hl.monitor({ output = "desc:Dell Inc. DELL P2217H RH81R83L0J7B",                         mode = "1920x1080@60.0",  position = "0x0",    scale = 1 })
hl.monitor({ output = "desc:Dell Inc. DELL P2217H 0G2TG7B51R8B",                         mode = "1920x1080@60.0",  position = "0x0",    scale = 1 })
hl.monitor({ output = "desc:LG Electronics LG HDR WFHD 0x00094E7F",                     mode = "2560x1080@59.98", position = "0x0",    scale = 1 })
hl.monitor({ output = "desc:Samsung Electric Company S24E650 0x5A5A5551",                mode = "1920x1080@60.0",  position = "0x0",    scale = 1 })
hl.monitor({ output = "desc:Philips Consumer Electronics Company PHL 276E8V 0x00000798", mode = "3840x2160@60.0",  position = "1920x0", scale = 1 })
hl.monitor({ output = "Virtual-1",                                                       mode = "1920x1440@60.0",  position = "0x0",    scale = 1 })
hl.monitor({ output = "",                                                                 mode = "preferred",       position = "auto",   scale = 1 })
