-- Generated by nwg-displays on 2024-07-24 at 08:45:25.
-- After switching to Lua, update these manually or via hyprctl.

hl.workspace_rule({ workspace = "4", monitor = "desc:Chimei Innolux Corporation 0x1521",   default = true })
hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL P2217H RH81R83L0J7B", default = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:Chimei Innolux Corporation 0x1521" })
hl.workspace_rule({ workspace = "1", monitor = "desc:Chimei Innolux Corporation 0x1521" })
