# AUTO-GENERATED by modules/theme. Do not edit. Run `nix build .#theme-render && cp -rT --no-preserve=mode result modules/home/common`.

{
  ansi = {
    black = "#21222c";
    blue = "#bd93f9";
    brightBlack = "#6272a4";
    brightBlue = "#d6acff";
    brightCyan = "#a4ffff";
    brightGreen = "#69ff94";
    brightMagenta = "#ff92df";
    brightRed = "#ff6e6e";
    brightWhite = "#ffffff";
    brightYellow = "#ffffa5";
    cyan = "#8be9fd";
    green = "#50fa7b";
    magenta = "#ff79c6";
    red = "#ff5555";
    white = "#f8f8f2";
    yellow = "#f1fa8c";
  };
  dracula = {
    background = "#282a36";
    comment = "#6272a4";
    cyan = "#8be9fd";
    foreground = "#f8f8f2";
    green = "#50fa7b";
    orange = "#ffb86c";
    pink = "#ff79c6";
    purple = "#bd93f9";
    red = "#ff5555";
    selection = "#44475a";
    yellow = "#f1fa8c";
  };
  elevation = [
    0
    1
    3
    6
    8
    12
  ];
  font = {
    family = {
      brand = "Roboto";
      icon = "Symbols Nerd Font Mono";
      mono = "JetBrainsMono Nerd Font Mono";
      plain = "Roboto";
      symbols = "Material Symbols Rounded";
    };
    scale = {
      bodyLarge = {
        font = "Roboto";
        lineHeight = 24;
        size = 16;
        tracking = 0.5;
        weight = 400;
      };
      bodyMedium = {
        font = "Roboto";
        lineHeight = 20;
        size = 14;
        tracking = 0.25;
        weight = 400;
      };
      bodySmall = {
        font = "Roboto";
        lineHeight = 16;
        size = 12;
        tracking = 0.4;
        weight = 400;
      };
      displayLarge = {
        font = "Roboto";
        lineHeight = 64;
        size = 57;
        tracking = -0.25;
        weight = 400;
      };
      displayMedium = {
        font = "Roboto";
        lineHeight = 52;
        size = 45;
        tracking = 0.0;
        weight = 400;
      };
      displaySmall = {
        font = "Roboto";
        lineHeight = 44;
        size = 36;
        tracking = 0.0;
        weight = 400;
      };
      headlineLarge = {
        font = "Roboto";
        lineHeight = 40;
        size = 32;
        tracking = 0.0;
        weight = 400;
      };
      headlineMedium = {
        font = "Roboto";
        lineHeight = 36;
        size = 28;
        tracking = 0.0;
        weight = 400;
      };
      headlineSmall = {
        font = "Roboto";
        lineHeight = 32;
        size = 24;
        tracking = 0.0;
        weight = 400;
      };
      labelLarge = {
        font = "Roboto";
        lineHeight = 20;
        size = 14;
        tracking = 0.1;
        weight = 500;
      };
      labelMedium = {
        font = "Roboto";
        lineHeight = 16;
        size = 12;
        tracking = 0.5;
        weight = 500;
      };
      labelSmall = {
        font = "Roboto";
        lineHeight = 16;
        size = 11;
        tracking = 0.5;
        weight = 500;
      };
      titleLarge = {
        font = "Roboto";
        lineHeight = 28;
        size = 22;
        tracking = 0.0;
        weight = 400;
      };
      titleMedium = {
        font = "Roboto";
        lineHeight = 24;
        size = 16;
        tracking = 0.15;
        weight = 500;
      };
      titleSmall = {
        font = "Roboto";
        lineHeight = 20;
        size = 14;
        tracking = 0.1;
        weight = 500;
      };
    };
  };
  motion = {
    css = {
      emphasized = "cubic-bezier(0.2, 0, 0, 1)";
      emphasizedAccelerate = "cubic-bezier(0.3, 0, 0.8, 0.15)";
      emphasizedDecelerate = "cubic-bezier(0.05, 0.7, 0.1, 1)";
      legacy = "cubic-bezier(0.4, 0, 0.2, 1)";
      legacyAccelerate = "cubic-bezier(0.4, 0, 1, 1)";
      legacyDecelerate = "cubic-bezier(0, 0, 0.2, 1)";
      linear = "cubic-bezier(0, 0, 1, 1)";
      standard = "cubic-bezier(0.2, 0, 0, 1)";
      standardAccelerate = "cubic-bezier(0.3, 0, 1, 1)";
      standardDecelerate = "cubic-bezier(0, 0, 0, 1)";
    };
    duration = {
      extraLong1 = 700;
      extraLong2 = 800;
      extraLong3 = 900;
      extraLong4 = 1000;
      long1 = 450;
      long2 = 500;
      long3 = 550;
      long4 = 600;
      medium1 = 250;
      medium2 = 300;
      medium3 = 350;
      medium4 = 400;
      short1 = 50;
      short2 = 100;
      short3 = 150;
      short4 = 200;
    };
    easing = {
      emphasized = [
        0.2
        0.0
        0.0
        1.0
      ];
      emphasizedAccelerate = [
        0.3
        0.0
        0.8
        0.15
      ];
      emphasizedDecelerate = [
        0.05
        0.7
        0.1
        1.0
      ];
      legacy = [
        0.4
        0.0
        0.2
        1.0
      ];
      legacyAccelerate = [
        0.4
        0.0
        1.0
        1.0
      ];
      legacyDecelerate = [
        0.0
        0.0
        0.2
        1.0
      ];
      linear = [
        0.0
        0.0
        1.0
        1.0
      ];
      standard = [
        0.2
        0.0
        0.0
        1.0
      ];
      standardAccelerate = [
        0.3
        0.0
        1.0
        1.0
      ];
      standardDecelerate = [
        0.0
        0.0
        0.0
        1.0
      ];
    };
  };
  palette = {
    error = "#ff5555";
    errorContainer = "#930016";
    inverseOnSurface = "#2e303c";
    inverseSurface = "#e1e1f1";
    onError = "#5c000a";
    onErrorContainer = "#ffdad7";
    onPrimary = "#411478";
    onPrimaryContainer = "#eddcff";
    onSecondary = "#620044";
    onSecondaryContainer = "#ffd8e9";
    onSuccess = "#003912";
    onSuccessContainer = "#69ff88";
    onSurface = "#f8f8f2";
    onSurfaceVariant = "#c5c5d5";
    onTertiary = "#00363e";
    onTertiaryContainer = "#a3eeff";
    onWarning = "#492900";
    onWarningContainer = "#ffdcbc";
    outline = "#6272a4";
    outlineVariant = "#44475a";
    primary = "#bd93f9";
    primaryContainer = "#593090";
    primaryFixed = "#eddcff";
    primaryFixedDim = "#d7baff";
    scrim = "#000000";
    secondary = "#ff79c6";
    secondaryContainer = "#860f60";
    secondaryFixed = "#ffd8e9";
    secondaryFixedDim = "#ffafd7";
    shadow = "#000000";
    success = "#50fa7b";
    successContainer = "#00531e";
    surface = "#11131e";
    surfaceBright = "#373845";
    surfaceContainer = "#1d1f2b";
    surfaceContainerHigh = "#282a36";
    surfaceContainerHighest = "#323440";
    surfaceContainerLow = "#191b26";
    surfaceContainerLowest = "#0b0e18";
    surfaceDim = "#11131e";
    tertiary = "#8be9fd";
    tertiaryContainer = "#004e5a";
    tertiaryFixed = "#a3eeff";
    tertiaryFixedDim = "#75d4e8";
    warning = "#ffb86c";
    warningContainer = "#683c00";
  };
  shape = {
    extraLarge = 28;
    extraSmall = 4;
    full = 9999;
    large = 16;
    medium = 12;
    none = 0;
    small = 8;
  };
  sizes = {
    notificationImage = 48;
    swayncAlbumArt = 96;
    swayncButtonCell = 109;
    swayncIcon = 24;
    swayncWidth = 500;
  };
  space = {
    extraLarge = 28;
    extraSmall = 4;
    large = 16;
    medium = 12;
    none = 0;
    small = 8;
  };
  state = {
    draggedOpacity = 0.16;
    focusOpacity = 0.12;
    hoverOpacity = 0.08;
    pressedOpacity = 0.12;
  };
  syntax = {
    bracketsParensBraces = {
      decoration = [ ];
      foreground = "#f8f8f2";
    };
    builtInFunctions = {
      decoration = [ ];
      foreground = "#8be9fd";
    };
    builtInMagicMethodsOrConstants = {
      decoration = [ ];
      foreground = "#bd93f9";
    };
    className = {
      decoration = [ ];
      foreground = "#8be9fd";
    };
    comment = {
      decoration = [ ];
      foreground = "#6272a4";
    };
    constant = {
      decoration = [ ];
      foreground = "#bd93f9";
    };
    constantEscapeSequences = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    cssParentSelectors = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    dateTime = {
      decoration = [ ];
      foreground = "#ffb86c";
    };
    decorators = {
      decoration = [ "italic" ];
      foreground = "#50fa7b";
    };
    deprecated = {
      background = "#bd93f9";
      decoration = [ ];
      foreground = "#f8f8f2";
    };
    destructuringAliasLhs = {
      decoration = [ "italic" ];
      foreground = "#ffb86c";
    };
    destructuringAliasRhs = {
      decoration = [ ];
      foreground = "#f8f8f2";
    };
    diffChanged = {
      decoration = [ ];
      foreground = "#ffb86c";
    };
    diffDeleted = {
      decoration = [ ];
      foreground = "#ff5555";
    };
    diffHeader = {
      decoration = [ ];
      foreground = "#6272a4";
    };
    diffInserted = {
      decoration = [ ];
      foreground = "#50fa7b";
    };
    diffText = {
      decoration = [ ];
      foreground = "#6272a4";
    };
    docCommentKeywords = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    docCommentParameters = {
      decoration = [ "italic" ];
      foreground = "#ffb86c";
    };
    docCommentTypes = {
      decoration = [ "italic" ];
      foreground = "#8be9fd";
    };
    error = {
      decoration = [ ];
      foreground = "#ff5555";
    };
    functionNames = {
      decoration = [ ];
      foreground = "#50fa7b";
    };
    functionParameters = {
      decoration = [ "italic" ];
      foreground = "#ffb86c";
    };
    genericTemplatesAndMappedDeclarations = {
      decoration = [ "italic" ];
      foreground = "#ffb86c";
    };
    htmlCssAttributeNames = {
      decoration = [ ];
      foreground = "#50fa7b";
    };
    htmlTags = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    inheritedClassName = {
      decoration = [ "italic" ];
      foreground = "#8be9fd";
    };
    instanceReservedWords = {
      decoration = [ "italic" ];
      foreground = "#bd93f9";
    };
    invalid = {
      background = "#ff5555";
      decoration = [ ];
      foreground = "#f8f8f2";
    };
    keys = {
      decoration = [ ];
      foreground = "#8be9fd";
    };
    keyword = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    keywordGenericCssSelector = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    keywordNew = {
      decoration = [ "bold" ];
      foreground = "#ff79c6";
    };
    markupBlockquote = {
      decoration = [ "italic" ];
      foreground = "#f1fa8c";
    };
    markupBold = {
      decoration = [ "bold" ];
      foreground = "#ffb86c";
    };
    markupCodeBlockWithoutSyntax = {
      decoration = [ ];
      foreground = "#ffb86c";
    };
    markupHeading = {
      decoration = [ "bold" ];
      foreground = "#bd93f9";
    };
    markupHorizontalRule = {
      decoration = [ ];
      foreground = "#6272a4";
    };
    markupInlineCode = {
      decoration = [ ];
      foreground = "#50fa7b";
    };
    markupItalic = {
      decoration = [ "italic" ];
      foreground = "#f1fa8c";
    };
    markupLinkText = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    markupLinkUrl = {
      decoration = [ ];
      foreground = "#8be9fd";
    };
    markupListBulletOrNumber = {
      decoration = [ ];
      foreground = "#8be9fd";
    };
    markupRstConstants = {
      decoration = [ ];
      foreground = "#bd93f9";
    };
    modifiers = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    objectKeys = {
      decoration = [ ];
      foreground = "#f8f8f2";
    };
    separatorsReferencesOrAccessors = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    storage = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    string = {
      decoration = [ ];
      foreground = "#f1fa8c";
    };
    stringInterpolationOperators = {
      decoration = [ ];
      foreground = "#ff79c6";
    };
    stringRegExp = {
      decoration = [ ];
      foreground = "#ff5555";
    };
    support = {
      decoration = [ "italic" ];
      foreground = "#8be9fd";
    };
    types = {
      decoration = [ "italic" ];
      foreground = "#8be9fd";
    };
    variable = {
      decoration = [ ];
      foreground = "#f8f8f2";
    };
    yamlAliases = {
      decoration = [
        "italic"
        "underline"
      ];
      foreground = "#50fa7b";
    };
  };
  weight = {
    bold = 700;
    medium = 500;
    regular = 400;
  };
}
