[manager]
layout = [6, 8, 8]
sort_by = "natural"
linemode = "size"
sort_sensitive = true
sort_reverse = true
sort_dir_first = true
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
open = [
	{ exec = 'xdg-open "$1"', desc = "Open", for = "linux" },
]

[open]
rules = [
	{ name = "*", use = [
		"open",
	] },
]

[tasks]
micro_workers = 8
macro_workers = 16
bizarre_retry = 5

[plugins]
preload = []

[log]
enabled = false
