/*
 * AUTO-GENERATED by modules/nix/theme.nix from modules/home/common/theme.
 * Do not edit. Regenerate with `nix build .#theme-render` and apply with
 * `cp -rT --no-preserve=mode result modules/home/common/config`.
 */

pragma Singleton

import QtQuick

QtObject {
    component PaletteTokens: QtObject {
        readonly property color m3error: "#ff5555"
        readonly property color m3errorContainer: "#930016"
        readonly property color m3inverseOnSurface: "#2e303c"
        readonly property color m3inverseSurface: "#e1e1f1"
        readonly property color m3onError: "#5c000a"
        readonly property color m3onErrorContainer: "#ffdad7"
        readonly property color m3onPrimary: "#411478"
        readonly property color m3onPrimaryContainer: "#eddcff"
        readonly property color m3onSecondary: "#620044"
        readonly property color m3onSecondaryContainer: "#ffd8e9"
        readonly property color m3onSuccess: "#003912"
        readonly property color m3onSuccessContainer: "#69ff88"
        readonly property color m3onSurface: "#f8f8f2"
        readonly property color m3onSurfaceVariant: "#c5c5d5"
        readonly property color m3onTertiary: "#00363e"
        readonly property color m3onTertiaryContainer: "#a3eeff"
        readonly property color m3onWarning: "#492900"
        readonly property color m3onWarningContainer: "#ffdcbc"
        readonly property color m3outline: "#6272a4"
        readonly property color m3outlineVariant: "#44475a"
        readonly property color m3primary: "#bd93f9"
        readonly property color m3primaryContainer: "#593090"
        readonly property color m3primaryFixed: "#eddcff"
        readonly property color m3primaryFixedDim: "#d7baff"
        readonly property color m3scrim: "#000000"
        readonly property color m3secondary: "#ff79c6"
        readonly property color m3secondaryContainer: "#860f60"
        readonly property color m3secondaryFixed: "#ffd8e9"
        readonly property color m3secondaryFixedDim: "#ffafd7"
        readonly property color m3shadow: "#000000"
        readonly property color m3success: "#50fa7b"
        readonly property color m3successContainer: "#00531e"
        readonly property color m3surface: "#11131e"
        readonly property color m3surfaceBright: "#373845"
        readonly property color m3surfaceContainer: "#1d1f2b"
        readonly property color m3surfaceContainerHigh: "#282a36"
        readonly property color m3surfaceContainerHighest: "#323440"
        readonly property color m3surfaceContainerLow: "#191b26"
        readonly property color m3surfaceContainerLowest: "#0b0e18"
        readonly property color m3surfaceDim: "#11131e"
        readonly property color m3tertiary: "#8be9fd"
        readonly property color m3tertiaryContainer: "#004e5a"
        readonly property color m3tertiaryFixed: "#a3eeff"
        readonly property color m3tertiaryFixedDim: "#75d4e8"
        readonly property color m3warning: "#ffb86c"
        readonly property color m3warningContainer: "#683c00"
    }

    component ShapeTokens: QtObject {
        readonly property int extraLarge: 28
        readonly property int extraSmall: 4
        readonly property int full: 9999
        readonly property int large: 16
        readonly property int medium: 12
        readonly property int none: 0
        readonly property int small: 8
    }

    component SpaceTokens: QtObject {
        readonly property int extraLarge: 28
        readonly property int extraSmall: 4
        readonly property int large: 16
        readonly property int medium: 12
        readonly property int none: 0
        readonly property int small: 8
    }

    component FontTokens: QtObject {
        readonly property string brand: "Roboto"
        readonly property string icon: "Symbols Nerd Font Mono"
        readonly property string mono: "JetBrainsMono Nerd Font Mono"
        readonly property string plain: "Roboto"
        readonly property int bodyLargeSize: 16
        readonly property int bodyLargeLine: 24
        readonly property int bodyLargeWeight: 400
        readonly property int bodyMediumSize: 14
        readonly property int bodyMediumLine: 20
        readonly property int bodyMediumWeight: 400
        readonly property int bodySmallSize: 12
        readonly property int bodySmallLine: 16
        readonly property int bodySmallWeight: 400
        readonly property int displayLargeSize: 57
        readonly property int displayLargeLine: 64
        readonly property int displayLargeWeight: 400
        readonly property int displayMediumSize: 45
        readonly property int displayMediumLine: 52
        readonly property int displayMediumWeight: 400
        readonly property int displaySmallSize: 36
        readonly property int displaySmallLine: 44
        readonly property int displaySmallWeight: 400
        readonly property int headlineLargeSize: 32
        readonly property int headlineLargeLine: 40
        readonly property int headlineLargeWeight: 400
        readonly property int headlineMediumSize: 28
        readonly property int headlineMediumLine: 36
        readonly property int headlineMediumWeight: 400
        readonly property int headlineSmallSize: 24
        readonly property int headlineSmallLine: 32
        readonly property int headlineSmallWeight: 400
        readonly property int labelLargeSize: 14
        readonly property int labelLargeLine: 20
        readonly property int labelLargeWeight: 500
        readonly property int labelMediumSize: 12
        readonly property int labelMediumLine: 16
        readonly property int labelMediumWeight: 500
        readonly property int labelSmallSize: 11
        readonly property int labelSmallLine: 16
        readonly property int labelSmallWeight: 500
        readonly property int titleLargeSize: 22
        readonly property int titleLargeLine: 28
        readonly property int titleLargeWeight: 400
        readonly property int titleMediumSize: 16
        readonly property int titleMediumLine: 24
        readonly property int titleMediumWeight: 500
        readonly property int titleSmallSize: 14
        readonly property int titleSmallLine: 20
        readonly property int titleSmallWeight: 500
    }

    component DurationTokens: QtObject {
        readonly property int extraLong1: 700
        readonly property int extraLong2: 800
        readonly property int extraLong3: 900
        readonly property int extraLong4: 1000
        readonly property int long1: 450
        readonly property int long2: 500
        readonly property int long3: 550
        readonly property int long4: 600
        readonly property int medium1: 250
        readonly property int medium2: 300
        readonly property int medium3: 350
        readonly property int medium4: 400
        readonly property int short1: 50
        readonly property int short2: 100
        readonly property int short3: 150
        readonly property int short4: 200
    }

    component StateTokens: QtObject {
        readonly property real draggedOpacity: 0.160000
        readonly property real focusOpacity: 0.120000
        readonly property real hoverOpacity: 0.080000
        readonly property real pressedOpacity: 0.120000
    }

    readonly property PaletteTokens palette: PaletteTokens {}
    readonly property ShapeTokens shape: ShapeTokens {}
    readonly property SpaceTokens space: SpaceTokens {}
    readonly property FontTokens font: FontTokens {}
    readonly property DurationTokens duration: DurationTokens {}
    readonly property StateTokens state: StateTokens {}
}
