#!/bin/bash

printf "Current cpu governor: "
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

printf "Change it to: Performance(p/P) or Powersave(s/S) \n"
read PREF

case $PREF in

  P | p)
    echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    ;;

  s | S)
    echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
    ;;

  *)
    printf "Abort. Unknown governor\n"
    ;;
esac

printf ""
read -p "Press any key to exit. " -n1 -s

