#!/bin/sh

set -eu

log_file=/tmp/dnsmasq-telemetry.log
max_bytes=1048576

if [ -p "$log_file" ]; then
	rm -f "$log_file"
fi
touch "$log_file"
chown dnsmasq:root "$log_file"
chmod 0660 "$log_file"
: > "$log_file"
exec 3< "$log_file"

while true; do
	if IFS= read -r line <&3; then
		case "$line" in
		*" dnsmasq-dhcp["*) tag=dnsmasq-dhcp ;;
		*) tag=dnsmasq ;;
		esac
		message=${line#*]: }
		logger -t "$tag" "$message"
		continue
	fi

	size=$(wc -c < "$log_file")
	if [ "$size" -gt "$max_bytes" ]; then
		exec 3<&-
		: > "$log_file"
		exec 3< "$log_file"
	fi
	sleep 1
done
