{ inputs, lib, ... }:
let
  inherit (inputs) infra-lib;

  types = infra-lib.lib.types { inherit lib; };

  inventory = infra-lib.lib.mkInventory {
    inherit lib types;
    inherit (inputs) self;
  };

  upstreamCodegen = infra-lib.lib.mkCodegen { inherit lib inventory; };
  emptyClusterRules = [
    "^secrets/cluster\\.yml$"
  ]
  ++ lib.mapAttrsToList (id: _: "^secrets/clusters/${id}\\.yml$") (
    lib.filterAttrs (_: cluster: (cluster.secret_paths or { }) == { }) inventory.clusters
  );
  codegen = upstreamCodegen // {
    sopsYaml =
      args@{ pkgs, ... }:
      let
        generated = upstreamCodegen.sopsYaml args;
      in
      pkgs.runCommand "sops-yaml"
        {
          nativeBuildInputs = [
            pkgs.jq
            pkgs.remarshal
          ];
          excludedRules = builtins.toJSON emptyClusterRules;
          passAsFile = [ "excludedRules" ];
        }
        ''
          remarshal -if yaml -of json -i ${generated} -o generated.json
          jq --slurpfile excluded "$excludedRulesPath" \
            '.creation_rules |= map(select(.path_regex as $path | ($excluded[0] | index($path) | not)))' \
            generated.json > filtered.json
          remarshal -if json -of yaml -i filtered.json -o body.yaml
          {
            printf '%s\n' '# AUTO-GENERATED by cluster-config codegen. Do not edit.'
            cat body.yaml
          } > "$out"
        '';
  };

  intent = infra-lib.lib.mkIntent { inherit lib inventory; };

  builder = infra-lib.lib.mkHost {
    inherit inputs lib inventory;
    inherit (inputs) self;
    libRoot = infra-lib;
  };

  hostFacts = infra-lib.lib.mkHostFacts inventory;
  kexecRootKeys = infra-lib.lib.mkKexecRootKeys inventory;
in
{
  flake = {
    lib = {
      inherit
        inventory
        codegen
        intent
        types
        hostFacts
        kexecRootKeys
        ;
    };

    inherit (builder) nixosConfigurations darwinConfigurations nixosModules;
  };
}
