{ inputs, lib, ... }:
let
  theme = import ../home/common/theme;

  configRoot = "modules/home/common/config";

  upperChars = lib.stringToCharacters "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  lowerChars = lib.stringToCharacters "abcdefghijklmnopqrstuvwxyz";
  kebab = builtins.replaceStrings upperChars (map (c: "-${c}") lowerChars);

  bannerLines = [
    "AUTO-GENERATED by modules/nix/theme.nix from modules/home/common/theme."
    "Do not edit. Regenerate with `nix build .#theme-render` and apply with"
    "`cp -rT --no-preserve=mode result modules/home/common/config`."
  ];

  cssBanner = "/*\n${lib.concatMapStringsSep "\n" (line: " * ${line}") bannerLines}\n */";
  hashBanner = lib.concatMapStringsSep "\n" (line: "# ${line}") bannerLines;

  defineColors =
    attrs:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "@define-color ${kebab name} ${value};") attrs
    );

  paletteCss = ''
    ${cssBanner}

    ${defineColors theme.dracula}

    ${defineColors theme.palette}
  '';

  # GTK CSS has no import mechanism that survives an arbitrary deploy root, so
  # each application receives its own copy of the shared palette.
  paletteConsumers = [
    "anyrun"
    "swaync"
    "wofi"
  ];

  # Configuration formats outside GTK CSS have no variables at all, so every
  # token a template needs has to be substituted before the file is written.
  prefixed =
    prefix: render: attrs:
    lib.mapAttrs' (name: value: lib.nameValuePair "${prefix}-${kebab name}" (render value)) attrs;

  tokenValues = {
    "font-brand" = theme.font.family.brand;
    "font-plain" = theme.font.family.plain;
    "font-mono" = theme.font.family.mono;
    "font-icon" = theme.font.family.icon;
  }
  // prefixed "colour" lib.id (theme.dracula // theme.palette)
  // prefixed "ansi" lib.id theme.ansi
  // prefixed "radius" toString theme.shape
  // prefixed "space" toString theme.space
  // prefixed "text" (role: toString role.size) theme.font.scale
  // prefixed "text-line" (role: toString role.lineHeight) theme.font.scale
  // prefixed "text-weight" (role: toString role.weight) theme.font.scale
  // prefixed "duration" toString theme.motion.duration
  // prefixed "state" toString theme.state
  // prefixed "easing" lib.id theme.motion.css
  // prefixed "size" toString theme.sizes;

  substitute = builtins.replaceStrings (map (name: "{{${name}}}") (lib.attrNames tokenValues)) (
    lib.attrValues tokenValues
  );

  template =
    banner: name: "${banner}\n\n${substitute (builtins.readFile (./theme/templates + "/${name}"))}";

  # Kitty's palette is exactly the Dracula ANSI table, so it is emitted from the
  # specification directly rather than kept as a template.
  kittyTheme =
    let
      pair = key: value: "${key} ${value}";
      inherit (theme) ansi;
      indexed = [
        ansi.black
        ansi.red
        ansi.green
        ansi.yellow
        ansi.blue
        ansi.magenta
        ansi.cyan
        ansi.white
        ansi.brightBlack
        ansi.brightRed
        ansi.brightGreen
        ansi.brightYellow
        ansi.brightBlue
        ansi.brightMagenta
        ansi.brightCyan
        ansi.brightWhite
      ];
    in
    ''
      ${hashBanner}
      # Palette source: https://spec.draculatheme.com

      ${pair "foreground" theme.dracula.foreground}
      ${pair "background" theme.dracula.background}
      ${pair "selection_foreground" ansi.brightWhite}
      ${pair "selection_background" theme.dracula.selection}

      ${pair "url_color" theme.dracula.cyan}

      ${lib.concatStringsSep "\n" (lib.imap0 (i: value: pair "color${toString i}" value) indexed)}

      ${pair "cursor" theme.dracula.foreground}
      cursor_text_color background

      ${pair "active_tab_foreground" theme.dracula.background}
      ${pair "active_tab_background" theme.dracula.foreground}
      ${pair "inactive_tab_foreground" theme.dracula.background}
      ${pair "inactive_tab_background" theme.dracula.comment}

      ${pair "mark1_foreground" theme.dracula.background}
      ${pair "mark1_background" theme.dracula.red}
    '';

  files =
    lib.listToAttrs (
      lib.concatMap (app: [
        (lib.nameValuePair "${app}/colors.css" paletteCss)
        (lib.nameValuePair "${app}/style.css" (template cssBanner "${app}.css.in"))
      ]) paletteConsumers
    )
    // {
      "kitty/dracula.conf" = kittyTheme;
      "tofi/config" = template hashBanner "tofi.config.in";
      "hypr/hyprlock.conf" = template hashBanner "hyprlock.conf.in";
      "quickshell/Theme.qml" = template cssBanner "quickshell.Theme.qml.in";
    };

  renderedPaths = lib.attrNames files;

  definedColours = lib.naturalSort (
    map kebab (lib.attrNames theme.dracula ++ lib.attrNames theme.palette)
  );

  # CSS at-rules that share the @name syntax but are not colour references.
  cssAtRules = [
    "charset"
    "import"
    "keyframes"
    "media"
    "supports"
  ];

  # Files whose colours are not theme colours and so are not palette-checked.
  paletteExempt = [
    # Gradient interpolation stops between palette colours.
    "btop/themes/*.theme"
    # Upstream Dracula theme with extended syntax roles beyond the specification.
    "QtProject/qtcreator/styles/*.xml"
    # Devicons filetype colours. The interface itself uses ANSI colour names,
    # which resolve through the generated terminal palette.
    "yazi/theme.toml"
  ];

  # CSS named colours, excluding "transparent" which carries no palette meaning.
  cssNamedColours = [
    "aqua"
    "black"
    "blue"
    "cyan"
    "fuchsia"
    "gray"
    "green"
    "grey"
    "lime"
    "magenta"
    "maroon"
    "navy"
    "olive"
    "orange"
    "pink"
    "purple"
    "red"
    "silver"
    "teal"
    "white"
    "yellow"
  ];
in
{
  perSystem =
    { pkgs, ... }:
    let
      rendered =
        pkgs.runCommand "theme-render"
          {
            nativeBuildInputs = [
              pkgs.prettier
              pkgs.qt6.qtdeclarative
            ];
          }
          ''
            mkdir -p "$out"
            ${lib.concatStringsSep "\n" (
              lib.mapAttrsToList (path: text: ''
                mkdir -p "$out/$(dirname ${lib.escapeShellArg path})"
                cp ${pkgs.writeText (baseNameOf path) text} "$out/${path}"
              '') files
            )}
            chmod -R u+w "$out"

            if grep -rn '{{' "$out"; then
              echo "theme-render: unsubstituted template token remains." >&2
              exit 1
            fi

            find "$out" -name '*.css' -exec prettier --write --parser css {} + > /dev/null
            find "$out" -name '*.qml' -exec qmlformat --inplace --ignore-settings --indent-width 4 {} +
          '';
    in
    {
      packages.theme-render = rendered;

      checks = {
        theme-drift =
          pkgs.runCommand "check-theme-drift"
            {
              src = inputs.self;
              inherit rendered;
            }
            ''
              failed=0

              for path in ${lib.escapeShellArgs renderedPaths}; do
                committed="$src/${configRoot}/$path"
                generated="$rendered/$path"

                if [ ! -e "$committed" ]; then
                  echo "theme-drift: missing committed file ${configRoot}/$path" >&2
                  failed=1
                  continue
                fi

                if ! diff -u "$committed" "$generated"; then
                  echo "theme-drift: ${configRoot}/$path differs from generated output" >&2
                  failed=1
                fi
              done

              if [ "$failed" -ne 0 ]; then
                echo "Regenerate with:" >&2
                echo "  nix build .#theme-render" >&2
                echo "  cp -rT --no-preserve=mode result ${configRoot}" >&2
                exit 1
              fi

              touch "$out"
            '';

        # An application's own stylesheet documents every element it can render.
        # Comparing against it catches both elements we never style and rules we
        # kept after the application renamed or removed the class.
        theme-coverage =
          if pkgs.stdenv.isLinux then
            pkgs.runCommand "check-theme-coverage"
              {
                src = inputs.self;
                nativeBuildInputs = [ pkgs.python3 ];
              }
              ''
                python3 ${./theme/coverage.py} \
                  ${pkgs.swaynotificationcenter}/etc/xdg/swaync/style.css \
                  "$src/${configRoot}/swaync/style.css"

                touch "$out"
              ''
          else
            pkgs.runCommand "check-theme-coverage" { } ''
              touch "$out"
            '';

        # A font whose italic face also advertises the "Regular" style name can be
        # matched for an upright request, which silently renders the interface in
        # italics. Variable cuts of some families do exactly this.
        theme-fonts =
          pkgs.runCommand "check-theme-fonts"
            {
              nativeBuildInputs = [
                pkgs.fontconfig
                pkgs.ripgrep
              ];
              fonts = pkgs.symlinkJoin {
                name = "theme-fonts";
                paths = [
                  pkgs.roboto
                  pkgs.nerd-fonts.jetbrains-mono
                  pkgs.nerd-fonts.symbols-only
                ];
              };
            }
            ''
              failed=0

              fc-scan --format '%{family}|%{style}\n' "$fonts/share/fonts" > faces.txt

              for family in ${lib.escapeShellArgs (lib.unique (lib.attrValues theme.font.family))}; do
                # The family field is a comma separated alias list, so whole
                # elements have to be compared rather than substrings.
                awk -F'|' -v want="$family" '
                  {
                    n = split($1, names, ",")
                    for (i = 1; i <= n; i++) {
                      if (names[i] == want) { print $2; next }
                    }
                  }
                ' faces.txt > styles.txt

                if [ ! -s styles.txt ]; then
                  echo "theme-fonts: family '$family' is not provided by any declared package." >&2
                  failed=1
                  continue
                fi

                # A style list naming both an italic and Regular lets the italic
                # face satisfy an upright request.
                if awk -F',' '
                  {
                    italic = 0; regular = 0
                    for (i = 1; i <= NF; i++) {
                      if ($i ~ /Italic/) italic = 1
                      if ($i == "Regular") regular = 1
                    }
                    if (italic && regular) { print "  offending style: " $0; found = 1 }
                  }
                  END { exit !found }
                ' styles.txt >&2; then
                  echo "theme-fonts: family '$family' has an italic face advertising the Regular style." >&2
                  failed=1
                fi
              done

              if [ "$failed" -ne 0 ]; then
                exit 1
              fi

              touch "$out"
            '';

        theme-tokens =
          pkgs.runCommand "check-theme-tokens"
            {
              src = inputs.self;
              nativeBuildInputs = [ pkgs.ripgrep ];
            }
            ''
                  failed=0
                  printf '%s\n' ${lib.escapeShellArgs definedColours} | sort -u > defined.txt

                  for app in ${lib.escapeShellArgs paletteConsumers}; do
                    style="$src/${configRoot}/$app/style.css"
                    [ -e "$style" ] || continue

                    if rg -n '#[0-9a-fA-F]{3,8}\b' "$style"; then
                      echo "theme-tokens: $app/style.css contains a literal hex colour." >&2
                      failed=1
                    fi

                    if rg -n 'rgba?\([0-9]' "$style"; then
                      echo "theme-tokens: $app/style.css contains a literal rgb colour." >&2
                      failed=1
                    fi

              template="$src/modules/nix/theme/templates/$app.css.in"

              # Font sizes must come from the type scale. "0" and "initial" are
              # resets rather than sizes, so they are allowed.
              if [ -e "$template" ] && rg -n 'font-size:\s*[0-9.]+(px|rem|pt|em)' "$template"; then
                echo "theme-tokens: $app.css.in has a font size outside the type scale." >&2
                failed=1
              fi

              # Spacing must come from the 4dp grid. 1px and 2px are hairlines.
              if [ -e "$template" ] && rg -n --pcre2 \
                '(?:padding|margin)(?:-(?:top|bottom|left|right))?:[^;]*(?<![.\d])-?(?:[3-9]|\d\d+)px' \
                "$template"; then
                echo "theme-tokens: $app.css.in has spacing outside the 4dp grid." >&2
                failed=1
              fi

              # Corner radii must come from the shape scale.
              if [ -e "$template" ] && rg -n --pcre2 \
                'border(?:-(?:top|bottom)-(?:left|right))?-radius:[^;]*(?<![.\d])[1-9]\d*px' \
                "$template"; then
                echo "theme-tokens: $app.css.in has a corner radius outside the shape scale." >&2
                failed=1
              fi

                  # Lookarounds keep hyphenated identifiers such as "blink-blue" from matching.
                    if rg -nP ${lib.escapeShellArg "(?<![-\\w@\"])(${lib.concatStringsSep "|" cssNamedColours})(?![-\\w])"} "$style"; then
                      echo "theme-tokens: $app/style.css contains a CSS named colour." >&2
                      failed=1
                    fi

                    rg -oN '@[a-zA-Z][a-zA-Z0-9-]*' "$style" \
                      | sed 's/^@//' \
                      | sort -u \
                      | rg -vx ${lib.escapeShellArgs [ (lib.concatStringsSep "|" cssAtRules) ]} \
                      > used.txt || true

                    if comm -13 defined.txt used.txt | rg .; then
                      echo "theme-tokens: $app/style.css references colours absent from $app/colors.css." >&2
                      failed=1
                    fi
                  done

                  printf '%s\n' ${
                    lib.escapeShellArgs (
                      lib.naturalSort (lib.attrValues (theme.dracula // theme.palette // theme.ansi))
                    )
                  } | tr 'A-F' 'a-f' | sort -u > palette.txt
                  tr -d '#' < palette.txt | sort -u > palette-bare.txt

                  # Hyprland is hand-maintained, so its colours are validated rather
                  # than generated. It writes colours as rgba(rrggbbaa) without a hash.
                  for config in "$src/${configRoot}"/hypr/*.lua "$src/${configRoot}"/hypr/*.conf; do
                    [ -e "$config" ] || continue

                    rg -oN --pcre2 '(?<=rgba?\()[0-9a-fA-F]{6}' "$config" | sort -u > hyprcolours.txt || true

                    if comm -13 palette-bare.txt hyprcolours.txt | rg .; then
                      echo "theme-tokens: $(basename "$config") uses a colour outside the palette." >&2
                      failed=1
                    fi
                  done

              # Every declared font family, generated or hand-maintained, must be
              # one of the token families.
              printf '%s\n' ${lib.escapeShellArgs (lib.unique (lib.attrValues theme.font.family))} | sort -u > families.txt

              rg -oIN --pcre2 \
                '(?:^\s*font_family\s*=?\s*|^\s*font\s*=\s*|font-family:\s*)\K[^;{}]+' \
                "$src/${configRoot}" \
                | tr ',' '\n' \
                | sed 's/^[[:space:]"]*//; s/[[:space:]";]*$//' \
                | rg -v '^$' \
                | sort -u > declared-families.txt || true

              if comm -13 families.txt declared-families.txt | rg .; then
                echo "theme-tokens: the families above are not in modules/home/common/theme." >&2
                failed=1
              fi

              # Pango markup accepts colour names, which resolve to their CSS
              # values rather than to anything in the palette.
                if rg -n --pcre2 "(?:foreground|background)='(?!#)" "$src/${configRoot}"; then
                  echo "theme-tokens: Pango markup must use palette hex, not a colour name." >&2
                  failed=1
                fi

                # Every other configuration file must only use palette colours.
                  while IFS= read -r config; do
                    case "''${config#"$src/${configRoot}/"}" in
                      ${lib.concatMapStringsSep "|" (glob: "${glob}") paletteExempt})
                        continue
                        ;;
                    esac

                    rg -oIN --pcre2 '#(?i)[0-9a-f]{6}\b' "$config" \
                      | tr 'A-F' 'a-f' | sort -u > filecolours.txt || true

                    if comm -13 palette.txt filecolours.txt | rg .; then
                      echo "theme-tokens: ''${config#"$src/${configRoot}/"} uses colours outside the palette." >&2
                      failed=1
                    fi
                  done < <(find "$src/${configRoot}" -type f)

                  if [ "$failed" -ne 0 ]; then
                    echo "Colours must come from modules/home/common/theme." >&2
                    exit 1
                  fi

                  touch "$out"
            '';
      };
    };
}
