theme = "tokyonight_storm"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Use system clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"
