theme = "dracula"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Use system clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
D = "delete_char_backward"
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
j = "move_line_down"
k = "move_line_up"

[keys.normal.space]
# g = ":pipe-to tmux split-window -h helix-live-grep"
"/" = ":pipe-to live-grep-in-split-tmux"
[keys.normal.g]
l = ["collapse_selection", "extend_to_line_end"]
h = ["collapse_selection", "extend_to_line_start"]
s = [
  "collapse_selection",
  "select_mode",
  "goto_first_nonwhitespace",
  "exit_select_mode",
]
a = ["save_selection"]
j = ["jump_forward"]
k = ["jump_backward"]

[editor]
true-color = true
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [80]
idle-timeout = 0
completion-trigger-len = 1

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
