theme = "dracula"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
# Use system clipboard
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"
D = "delete_char_backward"
J = ["extend_to_line_bounds", "delete_selection", "paste_after"]
K = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]
j = "move_line_down"
k = "move_line_up"

[keys.normal.space]
# g = ":pipe-to tmux split-window -h helix-live-grep"
g = ":pipe-to live-grep-in-split-tmux"

[editor]
line-number = "relative"
mouse = false
bufferline = "always"
rulers = [80]

[editor.cursor-shape]
insert = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.file-picker]
hidden = true

[editor.soft-wrap]
enable = true
