[language-server]
clangd = { command = "clangd", args = ['--fallback-style=Webkit'] }
texlab = { command = "texlab", config = { texlab = { build = { onSave = true, forwardSearchAfter = true }, forwardSearch = { executable = "sioyek", args = [
  "--execute-command",
  "turn_on_synctex;turn_on_presentation_mode",
  "--reuse-window",
  "%p",
  "--forward-search-file",
  "%f",
  "--forward-search-line",
  "%l",
] }, chktex = { onEdit = true } } } }

[[language]]
name = "python"
roots = ["pyproject.toml", "."]
language-servers = [ "pyright", "ruff" ]
auto-format = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
args = ["--ignore", "E501"]

[language.formatter]
command = "black"
args = ["--line-length", "88", "--quiet", "-"]
# Add this to pyproject.toml in root directory of project to add extra paths.
# [tool.pyright]
# extraPaths = ["./test"]


# [[language]]
# name = "verilog"
# formatter = { command = 'verible-verilog-format', args = ["-"] }
# auto-format = true
# indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
# auto-format = true

[[language]]
name = "toml"
auto-format = false

[[language]]
name = "cpp"
auto-format = true
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
auto-format = true
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }

# Diagnostics:
#   Suppress: "pp_including_mainfile_in_preamble"
# Add above codes into the .clangd file under your project directory.

# Create compile_commands.json using this: ` cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..`

[[language]]
name = "latex"
language-servers = ["texlab"]
