name: "Checks"
on:
  workflow_call:
permissions:
  contents: read
jobs:
  checks:
    uses: hakan-demirli/infra-lib/.github/workflows/checks.yml@e5b5879786e31adc5648cefb9e55bd0f99275ac9
  external-builds:
    uses: hakan-demirli/infra-lib/.github/workflows/external-builds.yml@e5b5879786e31adc5648cefb9e55bd0f99275ac9
