name: "Checks"
on:
  workflow_call:
permissions:
  contents: read
jobs:
  checks:
    uses: hakan-demirli/infra-lib/.github/workflows/checks.yml@ebecd0a6054b9d3734492fd3ac4f1ff7fe7951d9
  external-builds:
    uses: hakan-demirli/infra-lib/.github/workflows/external-builds.yml@ebecd0a6054b9d3734492fd3ac4f1ff7fe7951d9
