name: "Checks"
on:
  workflow_call:
permissions:
  contents: read
jobs:
  checks:
    uses: hakan-demirli/infra-lib/.github/workflows/checks.yml@b10033782a02978ff0254d1fca08f08c66bb49fd
  external-builds:
    uses: hakan-demirli/infra-lib/.github/workflows/external-builds.yml@b10033782a02978ff0254d1fca08f08c66bb49fd
