name: "Nix Build and Test"
on:
  push:
    branches: [main]
  workflow_dispatch:
  workflow_call:
permissions:
  contents: read
jobs:
  checks:
    uses: hakan-demirli/infra-lib/.github/workflows/checks.yml@d808b9056e49cd7e838a7255e28dd0d809ff4373
  external-builds:
    uses: hakan-demirli/infra-lib/.github/workflows/external-builds.yml@d808b9056e49cd7e838a7255e28dd0d809ff4373
  flake-check:
    needs: [checks, external-builds]
    if: always()
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - env:
          RESULTS: ${{ toJSON(needs) }}
        run: jq -e 'length == 2 and all(.[]; .result == "success")' <<< "$RESULTS"
