keys:
  - &master_key age1na2nkzg667cvcjsgse2t0fpf2fff350hp7zfvu96kg7q4nhjxe8seythl5

creation_rules:
  # Encrypt everything in this directory with the master key
  - path_regex: .*.yaml$
    key_groups:
      - age:
          - *master_key
