keys:
  - &personal age14p6ttyxnqv7qh3nwpdcs5uflau4hy6edr6fj4c7kyexjz7yekyyqr5lgn2
  - &fleet age150jk42s86el4wdr2w02heydgmqqu3gtuk4ypyxkwpftfmfcs94jqhzzuf4

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *personal
  - path_regex: tenants/.*\.yaml$
    key_groups:
      - age:
          - *fleet
