id = "openwrt-be10000"
state = "provisioned"

roles = ["external"]

[location]
kind = "network-equipment"

[ownership]
class = "personal"
owner = "user-0"
operator = "user-0"
custodian = "user-0"

[hardware]
arch = "aarch64-linux"
os = "openwrt"
cpu_vendor = "arm"

[labels]
role = "home-router"
external = "true"
ts_tag = "tag:personal-router"
